import type {
  GameDefinition,
  GameCategory,
  GameVariant,
  GameAvailability,
  GameMode,
  GameStakeEligibility,
  RulesVersion,
} from "./types";

export type GameMetadataInit = Omit<GameDefinition, "Board"> & {
  Board?: GameDefinition["Board"];
};

export const CANONICAL_GAMES_METADATA: readonly GameMetadataInit[] = [
  {
    id: "chess",
    nameKey: "chess",
    icon: "♟️",
    tagline: "The sovereign test of strategic calculation and positional mastery.",
    taglineAr: "قمة الرياضات الذهنية وحسابات المواقع التكتيكية.",
    shortDescription: "Standard FIDE blitz & rapid rules. Calculate moves ahead, control the center, and deliver checkmate.",
    shortDescriptionAr: "قواعد الشطرنج الخاطف والسريع الدولية. تحكيم خادم دقيق 100% وتحكم تكتيكي متكامل بدون أي حظ.",
    typicalDuration: "5–15 min",
    typicalDurationAr: "5–15 دقيقة",
    playerModeDisplay: "1v1 Head-to-Head",
    playerModeDisplayAr: "مبارزة 1 ضد 1",
    skillLevel: "All Levels · Master ELO",
    skillLevelAr: "جميع المستويات · تصنيف ELO",
    categories: ["ALL", "SKILL", "STRATEGY", "BOARD", "POPULAR", "AVAILABLE_NOW", "CASH_ELIGIBLE", "FREE_TO_PLAY"],
    isPopular: true,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 348,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: true,
      isFreeToPlay: true,
      minStakeUsd: 1,
      maxStakeUsd: 100,
      currency: "USDT",
    },
    rules: {
      version: "FIDE 2024",
      rulesUrl: "/games/chess",
      governingStandard: "FIDE Blitz / Rapid Standard",
      lastReviewedDate: "2026-09",
      hasRng: false,
    },
    variants: [
      { id: "blitz-3", name: "Blitz 3+2", nameAr: "خاطف 3+2", timeControl: "3m + 2s" },
      { id: "rapid-5", name: "Rapid 5+3", nameAr: "سريع 5+3", timeControl: "5m + 3s" },
      { id: "classic-10", name: "Standard 10m", nameAr: "كلاسيكي 10 د", timeControl: "10m" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Ranked Duel", labelAr: "مبارزة تصنيف 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب وتطوير المهارات", minPlayers: 1, maxPlayers: 1 },
      { type: "TOURNAMENT", label: "Championship Cup", labelAr: "بطولات الكؤوس", minPlayers: 8, maxPlayers: 128 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: true,
    cashEnabled: true,
  },
  {
    id: "dominoes",
    nameKey: "dominoes",
    icon: "🀄",
    tagline: "Mastery of tile reading, count blocking, and strategic chain control.",
    taglineAr: "فنون قراءة القطع، قفل الطاولة، وحسابات النقاط التكتيكية.",
    shortDescription: "Standard Draw Dominoes with end-matching rules. Block your rival, count remaining pips, and secure the board.",
    shortDescriptionAr: "لعبة الضمنة الكلاسيكية بنظام السحب والقفل. اقرأ قطع الخصم، احسب البوانط المتبقية، وسيطر على اللعبة.",
    typicalDuration: "5–10 min",
    typicalDurationAr: "5–10 دقائق",
    playerModeDisplay: "1v1 Head-to-Head",
    playerModeDisplayAr: "مبارزة 1 ضد 1",
    skillLevel: "Tactical · Counting",
    skillLevelAr: "تكتيكي · قراءة وحساب",
    categories: ["ALL", "SKILL", "STRATEGY", "BOARD", "POPULAR", "AVAILABLE_NOW", "CASH_ELIGIBLE", "FREE_TO_PLAY"],
    isPopular: true,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 292,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: true,
      isFreeToPlay: true,
      minStakeUsd: 1,
      maxStakeUsd: 100,
      currency: "USDT",
    },
    rules: {
      version: "v1.0",
      rulesUrl: "/games/dominoes",
      governingStandard: "International Draw Dominoes Standard",
      lastReviewedDate: "2026-09",
      hasRng: true,
      rngMechanism: "Server CSPRNG Tile Shuffle",
    },
    variants: [
      { id: "draw-standard", name: "Draw Dominoes", nameAr: "ضمنة سحب كلاسيكية" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب منفرد", minPlayers: 1, maxPlayers: 1 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: true,
    cashEnabled: true,
  },
  {
    id: "ludo",
    nameKey: "ludo",
    icon: "🎲",
    tagline: "The legendary token race! Tactical pathing, safe haven timing, and crown victory.",
    taglineAr: "سباق أساطير اللودو! مسارات تكتيكية، أمان النجوم، وتتويج الأبطال.",
    shortDescription: "Tournament Ludo for 2 to 4 players. Roll dice with server CSPRNG, maneuver 4 tokens, capture enemies, and race home.",
    shortDescriptionAr: "لودو البطولات الرسمية لـ 2 إلى 4 لاعبين. رميات نرد مشفرة، مناورة ذكية للرموز الأربعة، وقنص المنافسين نحو خط النهاية.",
    typicalDuration: "10–20 min",
    typicalDurationAr: "10–20 دقيقة",
    playerModeDisplay: "1v1 & 2–4 Players",
    playerModeDisplayAr: "1 ضد 1 و 2 إلى 4 لاعبين",
    skillLevel: "Tactical Race · Risk Management",
    skillLevelAr: "سباق تكتيكي · إدارة المخاطر",
    categories: ["ALL", "SKILL", "BOARD", "CASUAL", "NEW", "POPULAR", "AVAILABLE_NOW", "CASH_ELIGIBLE", "FREE_TO_PLAY"],
    isPopular: true,
    isNew: true,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 512,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: true,
      isFreeToPlay: true,
      minStakeUsd: 1,
      maxStakeUsd: 50,
      currency: "USDT",
    },
    rules: {
      version: "v1.1",
      rulesUrl: "/games/ludo",
      governingStandard: "Standard Tournament Ludo Championship",
      lastReviewedDate: "2026-09",
      hasRng: true,
      rngMechanism: "Server CSPRNG Dice Generator",
    },
    variants: [
      { id: "ludo-2p", name: "1v1 Duel", nameAr: "مبارزة ثنائية 1v1", playerCount: 2 },
      { id: "ludo-4p", name: "4-Player FFA", nameAr: "معركة رباعية 4 لاعبين", playerCount: 4 },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "2-4p", label: "4-Player Clash", labelAr: "نزال رباعي", minPlayers: 4, maxPlayers: 4 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب تكتيكي منفرد", minPlayers: 1, maxPlayers: 1 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: false,
    cashEnabled: true,
  },
  {
    id: "backgammon",
    nameKey: "backgammon",
    icon: "🎲",
    tagline: "The ancient mathematical game of pip movement, bearing off, and doubling risk.",
    taglineAr: "طاولة الزهر العريقة بحسابات المسافات وخروج القواشيط الذكي.",
    shortDescription: "Standard Backgammon with prime blockades and hit checks. Race your 15 checkers around the board and bear off first.",
    shortDescriptionAr: "طاولة الزهر العالمية بقواعد إغلاق الأبواب وضرب القواشيط والخروج السريع نحو النصر.",
    typicalDuration: "8–15 min",
    typicalDurationAr: "8–15 دقيقة",
    playerModeDisplay: "1v1 Head-to-Head",
    playerModeDisplayAr: "مبارزة 1 ضد 1",
    skillLevel: "Pip Strategy · Probability",
    skillLevelAr: "تكتيك مسافات · احتمالات",
    categories: ["ALL", "SKILL", "STRATEGY", "BOARD", "AVAILABLE_NOW", "CASH_ELIGIBLE", "FREE_TO_PLAY"],
    isPopular: false,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 218,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: true,
      isFreeToPlay: true,
      minStakeUsd: 1,
      maxStakeUsd: 100,
      currency: "USDT",
    },
    rules: {
      version: "WBF 2023",
      rulesUrl: "/games/backgammon",
      governingStandard: "World Backgammon Federation (WBF)",
      lastReviewedDate: "2026-09",
      hasRng: true,
      rngMechanism: "Server CSPRNG Dice",
    },
    variants: [
      { id: "standard-race", name: "Standard Backgammon", nameAr: "طاولة زهر كلاسيكية" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب منفرد", minPlayers: 1, maxPlayers: 1 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: false,
    cashEnabled: true,
  },
  {
    id: "speed-math",
    nameKey: "speed_math",
    icon: "🔢",
    tagline: "High-frequency mental arithmetic on a synchronized shared 60-second clock.",
    taglineAr: "أولمبياد الحساب الذهني فائق السرعة بساعة مشتركة متزامنة 60 ثانية.",
    shortDescription: "Synchronized real-time equations under pressure. 60 seconds of rapid addition, multiplication, and accuracy tests.",
    shortDescriptionAr: "معادلات رياضية سريعة متزامنة لحظياً. 60 ثانية من التحدي الذهني، والسرعة والدقة تحسم الفائز.",
    typicalDuration: "60 sec",
    typicalDurationAr: "60 ثانية",
    playerModeDisplay: "1v1 Blitz",
    playerModeDisplayAr: "مبارزة خاطفة 1v1",
    skillLevel: "Mental Speed · Pure Focus",
    skillLevelAr: "سرعة بديهة · تركيز مطلق",
    categories: ["ALL", "SKILL", "SPEED", "AVAILABLE_NOW", "CASH_ELIGIBLE", "FREE_TO_PLAY"],
    isPopular: false,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 210,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: true,
      isFreeToPlay: true,
      minStakeUsd: 1,
      maxStakeUsd: 50,
      currency: "USDT",
    },
    rules: {
      version: "v1.0",
      rulesUrl: "/games/speed-math",
      governingStandard: "Nizalo Speed Math Standard",
      lastReviewedDate: "2026-09",
      hasRng: false,
    },
    variants: [
      { id: "sprint-60", name: "60-Second Sprint", nameAr: "سباق 60 ثانية", timeControl: "60s" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
    ],
    turnModel: "SIMULTANEOUS",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: false,
    cashEnabled: true,
  },
  {
    id: "xo",
    nameKey: "xo",
    icon: "❌",
    tagline: "Fast-paced Tic-Tac-Toe blitz. Pure reaction speed and precision placement.",
    taglineAr: "إكس أو الخاطفة بالسرعة القصوى. ردود فعل فورية ودقة متناهية.",
    shortDescription: "Lightning 3x3 duel. 3 seconds per move to establish 3-in-a-row or force a tactical draw.",
    shortDescriptionAr: "مبارزة 3x3 خاطفة. 3 ثوانٍ لكل حركة لتحقيق ثلاثة في صف أو فرض التعادل التكتيكي.",
    typicalDuration: "1–2 min",
    typicalDurationAr: "1–2 دقيقة",
    playerModeDisplay: "1v1 Blitz",
    playerModeDisplayAr: "مبارزة خاطفة 1v1",
    skillLevel: "Reflexes · Zero Error",
    skillLevelAr: "سرعة رد فعل · بدون أخطاء",
    categories: ["ALL", "SKILL", "SPEED", "CASUAL", "POPULAR", "AVAILABLE_NOW", "FREE_TO_PLAY"],
    isPopular: true,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 435,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: false,
      isFreeToPlay: true,
      reasonIfNotEligible: "Free Only · Solved Game Policy",
      reasonIfNotEligibleAr: "مجاني فقط · مخصص للسرعة والتدريب",
    },
    rules: {
      version: "v1.0",
      rulesUrl: "/games/xo",
      governingStandard: "Classic 3x3 Tic-Tac-Toe Blitz",
      lastReviewedDate: "2026-09",
      hasRng: false,
    },
    variants: [
      { id: "xo-blitz", name: "3-Second Blitz", nameAr: "خاطفة 3 ثوانٍ" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب منفرد", minPlayers: 1, maxPlayers: 1 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: true,
    cashEnabled: false,
  },
  {
    id: "connect-four",
    nameKey: "connect_four",
    icon: "🔴",
    tagline: "Vertical gravity drop strategy. Spot alignment diagonals and construct traps.",
    taglineAr: "استراتيجية الإسقاط العمودي وبناء الفخاخ القطرية والأفقية.",
    shortDescription: "7 columns, 6 rows. Drop colored discs, deny opponent trajectories, and connect 4 in a row.",
    shortDescriptionAr: "شبكة 7×6 الشهيرة. أسقط أقراصك بذكاء، امنع خطوط الخصم، واربط 4 قطع متصلة.",
    typicalDuration: "3–5 min",
    typicalDurationAr: "3–5 دقائق",
    playerModeDisplay: "1v1 Head-to-Head",
    playerModeDisplayAr: "مبارزة 1 ضد 1",
    skillLevel: "Pattern Recognition",
    skillLevelAr: "تمييز الأنماط والذكاء المكاني",
    categories: ["ALL", "SKILL", "STRATEGY", "CASUAL", "AVAILABLE_NOW", "FREE_TO_PLAY"],
    isPopular: false,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 280,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: false,
      isFreeToPlay: true,
      reasonIfNotEligible: "Free Only · Solved Game Policy",
      reasonIfNotEligibleAr: "مجاني فقط · مخصص للتحدي المفتوح",
    },
    rules: {
      version: "v1.0",
      rulesUrl: "/games/connect-four",
      governingStandard: "Standard 7x6 Connect Four",
      lastReviewedDate: "2026-09",
      hasRng: false,
    },
    variants: [
      { id: "c4-standard", name: "Classic 7x6", nameAr: "كلاسيكي 7x6" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب منفرد", minPlayers: 1, maxPlayers: 1 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: true,
    cashEnabled: false,
  },
  {
    id: "checkers",
    nameKey: "checkers",
    icon: "⚫",
    tagline: "Mandatory multi-jump captures and king conversions on an 8x8 checkerboard.",
    taglineAr: "الداما الكلاسيكية بإلزامية القفز المتعدد وترقية الملوك على رقعة 8×8.",
    shortDescription: "American Checkers rules. Advance diagonally, execute mandatory jumps, promote to King, and capture all pieces.",
    shortDescriptionAr: "قواعد الداما الدولية المعتمدة. تقدم قطرياً، نفّذ القفز الإجباري، رقّ قطعك لملوك، واكتسح رقعة الخصم.",
    typicalDuration: "8–15 min",
    typicalDurationAr: "8–15 دقيقة",
    playerModeDisplay: "1v1 Head-to-Head",
    playerModeDisplayAr: "مبارزة 1 ضد 1",
    skillLevel: "Tactical Planning · Forced Lines",
    skillLevelAr: "تخطيط تكتيكي · مسارات إجبارية",
    categories: ["ALL", "SKILL", "STRATEGY", "BOARD", "AVAILABLE_NOW", "CASH_ELIGIBLE", "FREE_TO_PLAY"],
    isPopular: false,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 194,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: true,
      isFreeToPlay: true,
      minStakeUsd: 1,
      maxStakeUsd: 100,
      currency: "USDT",
    },
    rules: {
      version: "WCDF 2022",
      rulesUrl: "/games/checkers",
      governingStandard: "American Checkers Standard",
      lastReviewedDate: "2026-09",
      hasRng: false,
    },
    variants: [
      { id: "checkers-standard", name: "American Checkers", nameAr: "داما كلاسيكية" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب متقدم", minPlayers: 1, maxPlayers: 1 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: true,
    cashEnabled: true,
  },
  {
    id: "reversi",
    nameKey: "reversi",
    icon: "⚪",
    tagline: "A minute to learn, a lifetime to master. Edge trapping and disc flipping domination.",
    taglineAr: "دقيقة لتتعلمها، وعمر لتتقنها. السيطرة على الزوايا وقلب الأقراص الصادم.",
    shortDescription: "Classic 8x8 Othello/Reversi. Flank your opponent's discs to flip them to your color. Corner control is everything.",
    shortDescriptionAr: "ريفيرسي (عطيل) على رقعة 8×8. طوّق أقراص الخصم لتقلبها إلى لونك. من يسيطر على الزوايا يسيطر على النزال.",
    typicalDuration: "5–10 min",
    typicalDurationAr: "5–10 دقائق",
    playerModeDisplay: "1v1 Head-to-Head",
    playerModeDisplayAr: "مبارزة 1 ضد 1",
    skillLevel: "Positional Reversals · Territory",
    skillLevelAr: "انقلابات المواقع · السيطرة على الأطراف",
    categories: ["ALL", "SKILL", "STRATEGY", "BOARD", "AVAILABLE_NOW", "CASH_ELIGIBLE", "FREE_TO_PLAY"],
    isPopular: false,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 165,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: true,
      isFreeToPlay: true,
      minStakeUsd: 1,
      maxStakeUsd: 50,
      currency: "USDT",
    },
    rules: {
      version: "WOF 2023",
      rulesUrl: "/games/reversi",
      governingStandard: "World Othello Federation Standard",
      lastReviewedDate: "2026-09",
      hasRng: false,
    },
    variants: [
      { id: "reversi-standard", name: "Standard 8x8", nameAr: "كلاسيكي 8x8" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب منفرد", minPlayers: 1, maxPlayers: 1 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: true,
    cashEnabled: true,
  },
  {
    id: "gomoku",
    nameKey: "gomoku",
    icon: "🟢",
    tagline: "The five-stone alignment battle on a traditional goban intersections grid.",
    taglineAr: "معركة مصفوفة الأحجار الخمسة على تقاطعات رقعة الغو العريقة.",
    shortDescription: "Freestyle Gomoku. Place black and white stones on empty intersections to form an unbroken chain of 5 stones.",
    shortDescriptionAr: "غوموكو العالمية. ضع أحجارك على التقاطعات، ابنِ خطوط الهجوم المزدوج، وكوّن سلسلة متصلة من 5 أحجار.",
    typicalDuration: "5–10 min",
    typicalDurationAr: "5–10 دقائق",
    playerModeDisplay: "1v1 Head-to-Head",
    playerModeDisplayAr: "مبارزة 1 ضد 1",
    skillLevel: "Tactical Alignment · Foresight",
    skillLevelAr: "تكتيك المصفوفات · بعد النظر",
    categories: ["ALL", "SKILL", "STRATEGY", "BOARD", "AVAILABLE_NOW", "FREE_TO_PLAY"],
    isPopular: false,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 172,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: false,
      isFreeToPlay: true,
      reasonIfNotEligible: "Free Only · Open Challenge",
      reasonIfNotEligibleAr: "مجاني فقط · تدريب ومنافسة حرة",
    },
    rules: {
      version: "v1.0",
      rulesUrl: "/games/gomoku",
      governingStandard: "International Freestyle Gomoku",
      lastReviewedDate: "2026-09",
      hasRng: false,
    },
    variants: [
      { id: "gomoku-freestyle", name: "Freestyle 15x15", nameAr: "حر 15x15" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب منفرد", minPlayers: 1, maxPlayers: 1 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: true,
    cashEnabled: false,
  },
  {
    id: "seega",
    nameKey: "seega",
    icon: "🎯",
    tagline: "The timeless heritage mind sport of the Arab world. Placement, trapping, and encirclement.",
    taglineAr: "رياضة الأجداد الذهنية التراثية في العالم العربي. إنزال، تطويق، وقنص تكتيكي.",
    shortDescription: "Authentic Arab 5x5 Seega. Stage 1 placement, Stage 2 flanking captures. Surround opposing tokens to eliminate them.",
    shortDescriptionAr: "السيجة التراثية العربية الأصيلة على شبكة 5×5. مرحلة الإنزال ثم مرحلة التحريك والقنص بين قطعتين.",
    typicalDuration: "5–12 min",
    typicalDurationAr: "5–12 دقيقة",
    playerModeDisplay: "1v1 Head-to-Head",
    playerModeDisplayAr: "مبارزة 1 ضد 1",
    skillLevel: "Traditional Tactics · Pincer Encirclement",
    skillLevelAr: "تكتيك تراثي · تطويق ومحاصرة",
    categories: ["ALL", "SKILL", "STRATEGY", "BOARD", "AVAILABLE_NOW", "FREE_TO_PLAY"],
    isPopular: false,
    isNew: false,
    availability: {
      status: "LIVE",
      isAvailableNow: true,
      onlinePlayersBenchmark: 146,
      serversOnline: true,
    },
    stakeEligibility: {
      isCashEligible: false,
      isFreeToPlay: true,
      reasonIfNotEligible: "Free Only · Heritage Classic",
      reasonIfNotEligibleAr: "مجاني فقط · كلاسيكيات التراث",
    },
    rules: {
      version: "v1.0",
      rulesUrl: "/games/seega",
      governingStandard: "Authentic Arab Seega Heritage Standard",
      lastReviewedDate: "2026-09",
      hasRng: false,
    },
    variants: [
      { id: "seega-5x5", name: "Standard 5x5 Grid", nameAr: "شبكة 5×5 كلاسيكية" },
    ],
    modes: [
      { type: "1v1", label: "1v1 Duel", labelAr: "مبارزة 1v1", minPlayers: 2, maxPlayers: 2 },
      { type: "SOLO_AI", label: "Solo Training", labelAr: "تدريب منفرد", minPlayers: 1, maxPlayers: 1 },
    ],
    turnModel: "ALTERNATING",
    supportsAI: true,
    difficulties: ["EASY", "MEDIUM", "HARD", "EXPERT"],
    supportsDraw: true,
    cashEnabled: false,
  },
] as const;
