/**
 * Game Theme Tokens & Visual Identities System.
 * 
 * Defines distinct aesthetic atmospheres, color palettes, sound materials,
 * countdown vibes, victory insignias, and game-specific mode copywriting
 * for all 11 Nizalo games.
 * 
 * Ensures Nizalo Parent Brand unity while eliminating the "one generic template" feeling.
 */

import type { SoundMaterial } from "@/lib/game-audio";

export type VictoryInsigniaType =
  | "crown"
  | "domino-bone"
  | "ludo-star"
  | "cube-64"
  | "lightning-bolt"
  | "crossed-blades"
  | "quad-circle"
  | "king-blade"
  | "yin-yang"
  | "zen-stone"
  | "scarab";

export interface GameModeCopy {
  title: Record<string, string>;
  desc: Record<string, string>;
  tag: Record<string, string>;
  badge: Record<string, string>;
}

export interface GameThemeTokens {
  gameId: string;
  persona: Record<string, string>;
  tagline: Record<string, string>;
  soundMaterial: SoundMaterial;
  victoryInsignia: VictoryInsigniaType;
  countdownVibe: Record<string, string>;
  turnPulseColor: string;
  palette: {
    primary: string;
    accent: string;
    bg: string;
    surface: string;
    border: string;
    glow: string;
    text: string;
    cardGradient: string;
    tableRim: string;
  };
  modes: {
    ai: GameModeCopy;
    friend: GameModeCopy;
    match: GameModeCopy;
    tournament: GameModeCopy;
  };
}

export const GAME_THEME_TOKENS: Record<string, GameThemeTokens> = {
  chess: {
    gameId: "chess",
    persona: {
      ar: "صراع العقول والأساتذة الكبار",
      en: "The Grandmaster's Crucible",
      es: "El Crisol del Gran Maestro",
      fr: "Le Creuset du Grand Maître",
      hi: "ग्रैंडमास्टर की अग्निपरीक्षा",
      zh: "特级大师棋道决峰",
    },
    tagline: {
      ar: "معركة الملوك الخالدة بقواعد فيد (FIDE) الصارمة ونزاهة تامة",
      en: "The timeless battle of intellect under strict FIDE rules and anti-cheat",
      es: "La batalla eterna del intelecto bajo estrictas reglas FIDE",
      fr: "La bataille intemporelle de l'intellect selon les règles FIDE strictes",
      hi: "सख्त FIDE नियमों और निष्पक्षता के तहत बुद्धि की शाश्वत लड़ाई",
      zh: "在严谨国际棋联规则下的终极智力博弈",
    },
    soundMaterial: "wood",
    victoryInsignia: "crown",
    countdownVibe: {
      ar: "الملوك يستعدون.. النزال الملكي يبدأ الآن!",
      en: "Kings take their thrones.. The royal duel begins!",
      es: "¡Los reyes toman sus tronos.. Comienza el duelo real!",
      fr: "Les rois prennent place.. Le duel royal commence !",
      hi: "राजा सिंहासन पर आसीन.. शाही मुकाबला शुरू!",
      zh: "棋王升座.. 王者对弈即刻打响！",
    },
    turnPulseColor: "#f59e0b",
    palette: {
      primary: "#1e3a8a",
      accent: "#f59e0b",
      bg: "#080c18",
      surface: "#10192e",
      border: "rgba(245, 158, 11, 0.3)",
      glow: "rgba(245, 158, 11, 0.22)",
      text: "#f8fafc",
      cardGradient: "linear-gradient(145deg, rgba(30, 58, 138, 0.18) 0%, rgba(8, 12, 24, 0.95) 100%)",
      tableRim: "#1e293b",
    },
    modes: {
      ai: {
        title: {
          ar: "تحدي روبوت الماستر (مجاني)",
          en: "Master AI Arena (Free)",
          es: "Arena IA Gran Maestro (Gratis)",
          fr: "Arène IA Maître (Gratuit)",
          hi: "मास्टर एआई अखाड़ा (निःशुल्क)",
          zh: "大师AI特训场 (免费)",
        },
        desc: {
          ar: "تدرب على الافتتاحيات ونهايات الأدوار بدون مخاطرة مالية",
          en: "Hone your openings and endgames risk-free against 4 skill levels",
          es: "Practica aperturas y finales sin riesgo en 4 niveles",
          fr: "Perfectionnez vos ouvertures et finales sans risque",
          hi: "बिना किसी वित्तीय जोखिम के 4 स्तरों पर अपनी चालें तराशें",
          zh: "无财务风险打磨开局与残局战术，4档难度自由挑战",
        },
        tag: {
          ar: "تدريب استراتيجي",
          en: "Strategic Training",
          es: "Entrenamiento Estratégico",
          fr: "Entraînement Stratégique",
          hi: "रणनीतिक अभ्यास",
          zh: "战略实训",
        },
        badge: {
          ar: "مجاني 100%",
          en: "100% Free",
          es: "100% Gratis",
          fr: "100% Gratuit",
          hi: "100% मुफ़्त",
          zh: "完全免费",
        },
      },
      friend: {
        title: {
          ar: "تحدي خاص مع صديق",
          en: "Private FIDE Challenge",
          es: "Desafío FIDE Privado",
          fr: "Défi FIDE Privé",
          hi: "निजी FIDE चुनौती",
          zh: "好友专属国际象棋战",
        },
        desc: {
          ar: "اختر توقيت النقلة والرهان وأرسل الرابط مباشرة لصديقك",
          en: "Select time controls, set custom stakes, and invite via link",
          es: "Elige ritmo de juego, fija la apuesta y comparte el enlace",
          fr: "Choisissez la cadence, définissez l'enjeu et invitez par lien",
          hi: "समय नियंत्रण चुनें, कस्टम दांव लगाएं और लिंक से आमंत्रित करें",
          zh: "定制走棋时钟，设定比赛赌注，生成专属链接直接约战",
        },
        tag: {
          ar: "نزال ودّي أو رهانات",
          en: "Friendly or Cash Duel",
          es: "Amistoso o con Apuesta",
          fr: "Amical ou avec Mise",
          hi: "मैत्रीपूर्ण या नकद मुकाबला",
          zh: "好友切磋或真实奖池",
        },
        badge: {
          ar: "دعوة خاصة",
          en: "Direct Link",
          es: "Enlace Directo",
          fr: "Lien Direct",
          hi: "सीधा लिंक",
          zh: "专属链接",
        },
      },
      match: {
        title: {
          ar: "نزال تصنيفي تنافسي (1 ضد 1)",
          en: "Ranked Competitive Duel (1v1)",
          es: "Duelo Clasificatorio Competitivo",
          fr: "Duel Classé Compétitif (1v1)",
          hi: "रैंक्ड प्रतिस्पर्धी मुकाबला (1v1)",
          zh: "天梯排位金币决斗 (1对1)",
        },
        desc: {
          ar: "توفيق فوري ضد لاعب بنفس مستواك مع ساعة فيد ونظام مكافحة الغش",
          en: "Instant matchmaking with FIDE clocks and anti-cheat monitoring",
          es: "Emparejamiento instantáneo con reloj FIDE y anti-trampas",
          fr: "Matchmaking instantané avec horloge FIDE et anti-triche",
          hi: "FIDE घड़ियों और एंटी-चीट निगरानी के साथ तत्काल मैचमेकिंग",
          zh: "极速匹配同实力段对手，国际棋联时钟与全天候反作弊引擎护航",
        },
        tag: {
          ar: "جوائز فورية USDT",
          en: "Instant USDT Payout",
          es: "Pago USDT Instantáneo",
          fr: "Gain Immédiat en USDT",
          hi: "त्वरित USDT भुगतान",
          zh: "即时USDT奖金结算",
        },
        badge: {
          ar: "تنافسي موثق",
          en: "Ranked",
          es: "Clasificatorio",
          fr: "Classé",
          hi: "रैंक्ड",
          zh: "天梯排位",
        },
      },
      tournament: {
        title: {
          ar: "بطولات الإقصاء الكبرى للشطرنج",
          en: "Grand Knockout Chess Arena",
          es: "Grandes Torneos de Ajedrez",
          fr: "Grands Tournois d'Échecs",
          hi: "ग्रैंड नॉकआउट शतरंज टूर्नामेंट",
          zh: "国际象棋巅峰淘汰赛",
        },
        desc: {
          ar: "أدوار خروج المغلوب مع جوائز مالية كبرى للمراكز الأولى",
          en: "Single-elimination brackets with massive prize pools",
          es: "Cuadros de eliminación directa con grandes premios acumulados",
          fr: "Tableaux à élimination directe avec d'immenses cagnottes",
          hi: "विशाल पुरस्कार पूल के साथ सिंगल-एलिमिनेशन ब्रैकेट",
          zh: "经典单败淘汰争霸，晋级决战瓜分丰厚锦标赛奖池",
        },
        tag: {
          ar: "جوائز مجمّعة",
          en: "Prize Pools",
          es: "Botes de Premios",
          fr: "Cagnottes",
          hi: "पुरस्कार पूल",
          zh: "冠军大奖",
        },
        badge: {
          ar: "كؤوس وجوائز",
          en: "Major Trophy",
          es: "Gran Trofeo",
          fr: "Trophée Majeur",
          hi: "भव्य ट्रॉफी",
          zh: "争霸盛典",
        },
      },
    },
  },

  dominoes: {
    gameId: "dominoes",
    persona: {
      ar: "أسياد الدومينو والحساب الذكي",
      en: "Café Nostalgia & Bone Tactics",
      es: "Táctica de Huesos y Café Clásico",
      fr: "Maîtres des Dominos et Tactique",
      hi: "डोमिनोज़ उस्ताद और बुद्धि चाल",
      zh: "骨牌大师与算计风暴",
    },
    tagline: {
      ar: "لعبة المقاهي الكلاسيكية بين السحب العادي وحساب الخمسات الأمريكي (All-Fives)",
      en: "Classic Draw/Block table tension or fast-paced All-Fives 55 point sprint",
      es: "Tensión clásica de Robo/Cierre o la velocidad de All-Fives a 55 puntos",
      fr: "Tension classique de Pioche/Blocage ou sprint All-Fives à 55 points",
      hi: "पारंपरिक ड्रॉ/ब्लॉक मुकाबला या तेज़ ऑल-फाइव्स 55 अंकों की रेस",
      zh: "经典抽牌封局博弈与快节奏All-Fives 55分狂飙的巅峰对抗",
    },
    soundMaterial: "ceramic",
    victoryInsignia: "domino-bone",
    countdownVibe: {
      ar: "غسل البلاطات اكتمل.. الطاولة جاهزة للنزال!",
      en: "Tiles washed and shuffled.. The table is set!",
      es: "¡Fichas mezcladas.. La mesa está servida!",
      fr: "Tuiles mélangées.. La table est prête !",
      hi: "गोटियां मिल गईं.. टेबल मुकाबले के लिए तैयार!",
      zh: "骨牌洗匀码齐.. 牌局巅峰大战即刻开启！",
    },
    turnPulseColor: "#d97706",
    palette: {
      primary: "#78350f",
      accent: "#d97706",
      bg: "#120a06",
      surface: "#1f130b",
      border: "rgba(217, 119, 6, 0.3)",
      glow: "rgba(217, 119, 6, 0.2)",
      text: "#fef3c7",
      cardGradient: "linear-gradient(145deg, rgba(120, 53, 15, 0.22) 0%, rgba(18, 10, 6, 0.95) 100%)",
      tableRim: "#3e2723",
    },
    modes: {
      ai: {
        title: {
          ar: "تدريب منفرد مع البوت",
          en: "Solo Practice against Bot",
          es: "Práctica Solitaria con Bot",
          fr: "Entraînement Solo contre le Bot",
          hi: "बॉट के खिलाफ एकल अभ्यास",
          zh: "人机单人对抗实训",
        },
        desc: {
          ar: "جرب قفل اللعب أو سباق الخمسات بدون مخاطرة بأموالك",
          en: "Practice blocking lines or All-Fives scoring with zero risk",
          es: "Practica cierres o puntuación de All-Fives sin arriesgar saldo",
          fr: "Pratiquez le blocage ou le All-Fives sans risquer vos fonds",
          hi: "बिना किसी पैसे के जोखिम के लाइन ब्लॉक या ऑल-फाइव्स का अभ्यास करें",
          zh: "零风险操练封门杀阵与5的倍数算分打法",
        },
        tag: {
          ar: "مجاني بالكامل",
          en: "Free Play",
          es: "Juego Libre",
          fr: "Jeu Gratuit",
          hi: "मुफ़्त खेल",
          zh: "随心练习",
        },
        badge: {
          ar: "تدريب",
          en: "Practice",
          es: "Práctica",
          fr: "Pratique",
          hi: "अभ्यास",
          zh: "练习赛",
        },
      },
      friend: {
        title: {
          ar: "تحدي خاص بين الأصدقاء",
          en: "Private Table with Friend",
          es: "Mesa Privada con Amigos",
          fr: "Table Privée entre Amis",
          hi: "दोस्तों के साथ निजी टेबल",
          zh: "好友私密茶室约战",
        },
        desc: {
          ar: "أنشئ طاولة دومينو برهان محدد وشارك الرابط مع صديقك",
          en: "Create a custom domino room and share the link with a pal",
          es: "Crea una sala personalizada y comparte el enlace con un amigo",
          fr: "Créez une table personnalisée et invitez un ami via lien direct",
          hi: "कस्टम डोमिनोज़ रूम बनाएं और लिंक अपने दोस्त के साथ साझा करें",
          zh: "自由开辟专属骨牌战桌，定注发链一键邀约",
        },
        tag: {
          ar: "غرفة خاصة",
          en: "Private Room",
          es: "Sala Privada",
          fr: "Salon Privé",
          hi: "निजी कक्ष",
          zh: "专属包厢",
        },
        badge: {
          ar: "رابط مباشر",
          en: "Direct Link",
          es: "Enlace Directo",
          fr: "Lien Direct",
          hi: "सीधा लिंक",
          zh: "直约链接",
        },
      },
      match: {
        title: {
          ar: "نزال دومينو سريع (1 ضد 1)",
          en: "Quick Domino Duel (1v1)",
          es: "Duelo Rápido de Dominó (1v1)",
          fr: "Duel Rapide de Dominos (1v1)",
          hi: "त्वरित डोमिनोज़ मुकाबला (1v1)",
          zh: "骨牌即时现金对决 (1对1)",
        },
        desc: {
          ar: "توفيق فوري على الطاولة العادية أو نظام الخمسات مع أرباح نقدية",
          en: "Instant matchmaking for Traditional or All-Fives with cash prizes",
          es: "Emparejamiento al instante en Tradicional o All-Fives con premios",
          fr: "Matchmaking instantané en Traditionnel ou All-Fives avec prix en cash",
          hi: "पारंपरिक या ऑल-फाइव्स में तत्काल मैच और नकद जीत",
          zh: "经典抽牌与All-Fives玩法极速寻觅实力对手，赢取真金奖励",
        },
        tag: {
          ar: "جوائز نقدية فورية",
          en: "Instant Cash Rewards",
          es: "Premios en Efectivo",
          fr: "Récompenses Cash",
          hi: "तत्काल नकद पुरस्कार",
          zh: "真金奖金",
        },
        badge: {
          ar: "تنافسي فوري",
          en: "Instant Match",
          es: "Partida Rápida",
          fr: "Match Rapide",
          hi: "त्वरित मैच",
          zh: "极速秒配",
        },
      },
      tournament: {
        title: {
          ar: "بطولة عمالقة الدومينو",
          en: "Domino Masters Tournament",
          es: "Torneo de Maestros del Dominó",
          fr: "Tournoi des Maîtres du Domino",
          hi: "डोमिनोज़ मास्टर्स टूर्नामेंट",
          zh: "骨牌至尊锦标争霸赛",
        },
        desc: {
          ar: "سلسلة جولات متتالية لتحديد بطل الطاولة النهائي",
          en: "Multi-round knockout brackets to crown the tabletop champion",
          es: "Fases eliminatorias consecutivas para coronar al campeón de la mesa",
          fr: "Phases éliminatoires successives pour couronner le grand champion",
          hi: "टेबल चैंपियन का ताज पहनने के लिए मल्टी-राउंड नॉकआउट ब्रैकेट",
          zh: "多轮单淘汰捉对厮杀，决胜桌顶问鼎骨牌至尊荣耀",
        },
        tag: {
          ar: "كأس البطولة",
          en: "Championship",
          es: "Campeonato",
          fr: "Championnat",
          hi: "चैम्पियनशिप",
          zh: "冠军锦标",
        },
        badge: {
          ar: "جوائز ضخمة",
          en: "Huge Pool",
          es: "Gran Bote",
          fr: "Grosse Cagnotte",
          hi: "बड़ा पूल",
          zh: "巨额池金",
        },
      },
    },
  },

  ludo: {
    gameId: "ludo",
    persona: {
      ar: "سباق الأساطير والنرد الذهبي",
      en: "The Arcade Royale",
      es: "La Carrera de Leyendas",
      fr: "La Course des Légendes",
      hi: "दिग्गजों की लूडो दौड़",
      zh: "传奇飞行棋与狂飙金骰",
    },
    tagline: {
      ar: "إثارة النرد والمربعات الآمنة وحصن المثلث الذهبي لـ 2 أو 4 لاعبين",
      en: "Adrenaline-fueled dice rolls, safe star zones, and final home sprints",
      es: "Emoción de dados, casillas de estrellas seguras y carreras a meta",
      fr: "Adrénaline des dés, cases étoiles sécurisées et sprint final au centre",
      hi: "पासे का रोमांच, सुरक्षित स्टार क्षेत्र और अंतिम घर तक रोमांचक रेस",
      zh: "八大安全星格与中枢金三角撞线狂欢，支持2人或4人大乱斗",
    },
    soundMaterial: "ceramic",
    victoryInsignia: "ludo-star",
    countdownVibe: {
      ar: "القواطع جاهزة في القواعد.. النرد الذهبي يبدأ الدوران!",
      en: "Tokens positioned in bases.. Golden dice roll commences!",
      es: "¡Fichas listas en base.. Comienza el giro del dado dorado!",
      fr: "Pions prêts aux bases.. Le dé d'or commence à rouler !",
      hi: "गोटी बेस में तैयार.. सुनहरे पासे का चक्र शुरू!",
      zh: "四大阵营棋子归位.. 黄金骰子轰然开掷！",
    },
    turnPulseColor: "#10b981",
    palette: {
      primary: "#065f46",
      accent: "#10b981",
      bg: "#091219",
      surface: "#0f232c",
      border: "rgba(16, 185, 129, 0.35)",
      glow: "rgba(16, 185, 129, 0.25)",
      text: "#ecfdf5",
      cardGradient: "linear-gradient(145deg, rgba(16, 185, 129, 0.2) 0%, rgba(9, 18, 25, 0.95) 100%)",
      tableRim: "#1e3a47",
    },
    modes: {
      ai: {
        title: {
          ar: "تدريب لودو منفرد (بوتات)",
          en: "Solo Ludo Royale vs Bots",
          es: "Ludo Royale Solitario vs Bots",
          fr: "Ludo Royale Solo contre Bots",
          hi: "बॉट्स के खिलाफ सोलो लूडो रॉयल",
          zh: "单手机甲飞行棋特训",
        },
        desc: {
          ar: "العب ضد الروبوت في نزال 1 ضد 1 أو 4 لاعبين وتعلّم التكتيك",
          en: "Play 1v1 or 4-Player Free-for-all against smart AI bots",
          es: "Juega 1v1 o 4 jugadores contra bots de IA sin riesgo",
          fr: "Jouez en 1c1 ou à 4 joueurs contre des bots IA sans risque",
          hi: "स्मार्ट एआई बॉट्स के खिलाफ 1v1 या 4-खिलाड़ी फ्री-फॉर-ऑल खेलें",
          zh: "与智能电脑展开1对1单挑或4人混战，熟练走子与吃子战法",
        },
        tag: {
          ar: "بدون مخاطرة",
          en: "Zero Risk",
          es: "Sin Riesgo",
          fr: "Sans Risque",
          hi: "जोखिम रहित",
          zh: "零风险娱乐",
        },
        badge: {
          ar: "تدريب مجاني",
          en: "Free Play",
          es: "Práctica Libre",
          fr: "Entraînement",
          hi: "मुफ़्त अभ्यास",
          zh: "免费演练",
        },
      },
      friend: {
        title: {
          ar: "تحدي الأصدقاء في صالة لودو",
          en: "Private Ludo Room with Friends",
          es: "Sala Privada de Ludo con Amigos",
          fr: "Salle Privée de Ludo entre Amis",
          hi: "दोस्तों के साथ निजी लूडो रूम",
          zh: "好友专属飞行棋贵宾厅",
        },
        desc: {
          ar: "أنشئ طاولة لودو 2 أو 4 لاعبين وشارك الرمز فوراً في الشات",
          en: "Host 2-Player duel or 4-Player party and share room link",
          es: "Organiza partidas para 2 o 4 jugadores y comparte el código",
          fr: "Hébergez une partie à 2 ou 4 joueurs et partagez le lien",
          hi: "2 या 4 खिलाड़ियों का मैच होस्ट करें और सीधे रूम लिंक साझा करें",
          zh: "自定义双人决战或四人狂欢房，直链呼朋唤友即刻开战",
        },
        tag: {
          ar: "2 أو 4 لاعبين",
          en: "2 or 4 Players",
          es: "2 o 4 Jugadores",
          fr: "2 ou 4 Joueurs",
          hi: "2 या 4 खिलाड़ी",
          zh: "2人/4人同台",
        },
        badge: {
          ar: "غرفة خاصة",
          en: "Private Host",
          es: "Sala Privada",
          fr: "Hôte Privé",
          hi: "निजी मेजबान",
          zh: "私享房间",
        },
      },
      match: {
        title: {
          ar: "سباق لودو التنافسي (1 ضد 1)",
          en: "Ranked Ludo Sprint (1v1)",
          es: "Carrera Clasificatoria de Ludo",
          fr: "Course Classée de Ludo (1v1)",
          hi: "रैंक्ड लूडो स्प्रिंट (1v1)",
          zh: "天梯飞行棋金币竞速 (1对1)",
        },
        desc: {
          ar: "توفيق فوري ضد منافس حقيقي بقواعد عادلة وأرباح مباشرة",
          en: "Instant 1v1 duel with guaranteed fair dice and real-money pot",
          es: "Duelo 1v1 con dados certificados e indemnización inmediata",
          fr: "Duel 1c1 instantané avec dés certifiés et gains réels",
          hi: "प्रमाणित निष्पक्ष पासे और वास्तविक पुरस्कार के साथ तत्काल 1v1 मुकाबला",
          zh: "权威随机数骰子保障公平竞技，冲入金三角即刻结算奖池",
        },
        tag: {
          ar: "جوائز نقدية فورية",
          en: "Cash Prize Pool",
          es: "Bote en Efectivo",
          fr: "Cagnotte en Cash",
          hi: "नकद पुरस्कार पूल",
          zh: "赢取真金",
        },
        badge: {
          ar: "تنافسي 1 ضد 1",
          en: "1v1 Duel",
          es: "Duelo 1v1",
          fr: "Duel 1c1",
          hi: "1v1 मुकाबला",
          zh: "1v1对战",
        },
      },
      tournament: {
        title: {
          ar: "بطولة ملوك النرد والساحة",
          en: "Ludo Grand Arena Cup",
          es: "Copa Gran Arena de Ludo",
          fr: "Coupe Grand Arena de Ludo",
          hi: "लूडो ग्रैंड एरिना कप",
          zh: "飞行棋王者争霸公开赛",
        },
        desc: {
          ar: "تصفيات إقصائية كبرى ومنافسات على المركز الأول",
          en: "Championship brackets where only the fastest finisher triumphs",
          es: "Cuadros de campeonato donde solo triunfa el más veloz en meta",
          fr: "Arbre de championnat où seul le plus rapide l'emporte",
          hi: "चैम्पियनशिप ब्रैकेट जहाँ सबसे तेज़ विजेता ही ताज पाता है",
          zh: "单败淘汰阶梯晋级，唯有最快会师终点者方能登顶封王",
        },
        tag: {
          ar: "جوائز كبرى",
          en: "Grand Prizes",
          es: "Grandes Premios",
          fr: "Grands Prix",
          hi: "भव्य पुरस्कार",
          zh: "巨额大奖",
        },
        badge: {
          ar: "كأس البطولة",
          en: "Trophy Cup",
          es: "Copa Trofeo",
          fr: "Coupe Trophée",
          hi: "ट्रॉफी कप",
          zh: "锦标金杯",
        },
      },
    },
  },

  backgammon: {
    gameId: "backgammon",
    persona: {
      ar: "طاولة الملوك والزهر العريق",
      en: "Levant Tawla Luxury",
      es: "Lujo de Tawla y Reyes",
      fr: "Luxe Oriental du Tawla",
      hi: "शाही तवला और पासा विरासत",
      zh: "黎凡特东方双陆奢享",
    },
    tagline: {
      ar: "أعرق ألعاب الشرق بمكعب المضاعفة (64x) وقوانين كروفورد والغامون المضاعف",
      en: "Imperial board tactics with 64x Doubling Cube, Gammon & Crawford rules",
      es: "Táctica imperial con dado doblador 64x, reglas Gammon y Crawford",
      fr: "Tactique impériale avec videau 64x, règles du Gammon et Crawford",
      hi: "64x डबलिंग क्यूब, गैमन और क्रॉफर्ड नियमों के साथ शाही रणनीति",
      zh: "融入64倍双倍骰博弈、全盘大胜(Gammon)与克劳福德规则的千年巅峰博弈",
    },
    soundMaterial: "wood",
    victoryInsignia: "cube-64",
    countdownVibe: {
      ar: "الزهر العاجي يهتز في الكوب.. المعركة الشرقية تبدأ!",
      en: "Ivory dice rattle in the cup.. The imperial battle ignites!",
      es: "¡Los dados de marfil resuenan en el cubilete.. Inicia la contienda!",
      fr: "Les dés d'ivoire tintent dans le cornet.. La bataille s'embrase !",
      hi: "कप में हाथीदांत पासा खड़क रहा है.. शाही मुकाबला शुरू!",
      zh: "真木骰盅鸣响摇荡.. 东方千年双陆战火瞬间点燃！",
    },
    turnPulseColor: "#d4af37",
    palette: {
      primary: "#5c3a21",
      accent: "#d4af37",
      bg: "#140c07",
      surface: "#24150c",
      border: "rgba(212, 175, 55, 0.35)",
      glow: "rgba(212, 175, 55, 0.22)",
      text: "#fbf6ec",
      cardGradient: "linear-gradient(145deg, rgba(92, 58, 33, 0.22) 0%, rgba(20, 12, 7, 0.95) 100%)",
      tableRim: "#4a2c16",
    },
    modes: {
      ai: {
        title: {
          ar: "مبارزة الروبوت في طاولة الزهر",
          en: "Solo Tawla vs AI",
          es: "Tawla Solitario contra IA",
          fr: "Tawla Solo contre l'IA",
          hi: "एआई के खिलाफ सोलो तवला",
          zh: "智能双陆人机博弈训练",
        },
        desc: {
          ar: "تدرّب على حساب الاحتمالات وقفل الحصون بدون مخاطرة مالية",
          en: "Master prime structures and bearing-off odds risk-free",
          es: "Domina las estructuras de bloqueo y probabilidades sin riesgo",
          fr: "Maîtrisez les blocages et probabilités de sortie sans risque",
          hi: "बिना जोखिम के प्राइम स्ट्रक्चर और संभावनाओं का अभ्यास करें",
          zh: "零本钱推演封锁长蛇防线与快速出子胜率模型",
        },
        tag: {
          ar: "حساب الاحتمالات",
          en: "Odds Mastery",
          es: "Probabilidades",
          fr: "Probabilités",
          hi: "संभावनाएं",
          zh: "概率演练",
        },
        badge: {
          ar: "تدريب مجاني",
          en: "Free Training",
          es: "Entrenamiento",
          fr: "Entraînement",
          hi: "मुफ़्त प्रशिक्षण",
          zh: "实训模式",
        },
      },
      friend: {
        title: {
          ar: "تحدي خاص مع خبير طاولة",
          en: "Private Backgammon Duel",
          es: "Duelo Privado de Backgammon",
          fr: "Duel Privé de Backgammon",
          hi: "निजी बैकगैमौन मुकाबला",
          zh: "好友私密双陆约局",
        },
        desc: {
          ar: "حدد نقاط المباراة (1 أو 3 أو 5 نقاط) مع مكعب المضاعفة",
          en: "Set match points (1, 3, or 5) and challenge a friend directly",
          es: "Fija los puntos (1, 3 o 5) con dado doblador e invita a un amigo",
          fr: "Définissez les points de match (1, 3 ou 5) et invitez un ami",
          hi: "मैच अंक (1, 3, या 5) सेट करें और सीधे दोस्त को चुनौती दें",
          zh: "自由选定1/3/5分制长盘或单局决胜，支持双倍骰",
        },
        tag: {
          ar: "مكعب المضاعفة متاح",
          en: "Cube Enabled",
          es: "Dado Doblador",
          fr: "Videau Inclus",
          hi: "डबलिंग क्यूब सक्षम",
          zh: "加倍骰开启",
        },
        badge: {
          ar: "غرفة خاصة",
          en: "Private Duel",
          es: "Duelo Privado",
          fr: "Duel Privé",
          hi: "निजी मुकाबला",
          zh: "好友房",
        },
      },
      match: {
        title: {
          ar: "نزال الطاولة التنافسي (1 ضد 1)",
          en: "Ranked Backgammon Arena (1v1)",
          es: "Arena Clasificatoria de Backgammon",
          fr: "Arène Classée de Backgammon (1v1)",
          hi: "रैंक्ड बैकगैमौन अखाड़ा (1v1)",
          zh: "天梯排位双陆金币擂台 (1对1)",
        },
        desc: {
          ar: "توفيق فوري ضد محترفي الطاولة بنظام احتساب غامون وباكغامون المضاعف",
          en: "Instant matchmaking with Gammon & Backgammon payout multipliers",
          es: "Emparejamiento instantáneo con multiplicadores Gammon y Backgammon",
          fr: "Matchmaking instantané avec multiplicateurs Gammon et Backgammon",
          hi: "गैमन और बैकगैमौन भुगतान गुणक के साथ त्वरित मुकाबला",
          zh: "极速匹配同段位双陆高手，全盘大胜(Gammon)直接翻倍夺冠",
        },
        tag: {
          ar: "مضاعفات نقدية 2x و 3x",
          en: "2x & 3x Multipliers",
          es: "Multiplicadores 2x y 3x",
          fr: "Multiplicateurs 2x et 3x",
          hi: "2x और 3x गुणक",
          zh: "2倍/3倍翻倍奖金",
        },
        badge: {
          ar: "تنافسي موثق",
          en: "Ranked Arena",
          es: "Arena Oficial",
          fr: "Arène Officielle",
          hi: "आधिकारिक अखाड़ा",
          zh: "官方排位",
        },
      },
      tournament: {
        title: {
          ar: "كأس سلاطين الطاولة الكبرى",
          en: "Sultans of the Board Cup",
          es: "Copa Sultanes del Tablero",
          fr: "Coupe des Sultans du Tablier",
          hi: "बोर्ड सुल्तान कप",
          zh: "双陆苏丹至尊杯赛",
        },
        desc: {
          ar: "سلسلة مباريات إقصائية لتتويج سلطان الطاولة الأكبر",
          en: "Grand tournament brackets featuring multi-point series and huge pots",
          es: "Torneo eliminatorio con series a puntos y grandes premios",
          fr: "Arbre de tournoi majeur avec séries aux points et grosses cagnottes",
          hi: "मल्टी-पॉइंट सीरीज़ और विशाल पुरस्कारों के साथ भव्य टूर्नामेंट",
          zh: "多点积分晋级制单淘汰淘汰赛，问鼎双陆苏丹宝座",
        },
        tag: {
          ar: "جوائز كبرى",
          en: "Grand Trophy",
          es: "Gran Trofeo",
          fr: "Grand Trophée",
          hi: "भव्य ट्रॉफी",
          zh: "至尊大奖",
        },
        badge: {
          ar: "كأس البطولة",
          en: "Major Cup",
          es: "Copa Mayor",
          fr: "Grande Coupe",
          hi: "प्रमुख कप",
          zh: "巅峰奖杯",
        },
      },
    },
  },

  "speed-math": {
    gameId: "speed-math",
    persona: {
      ar: "معركة العباقرة والسرعة الخارقة",
      en: "Neural Velocity & Fast Synapse",
      es: "Velocidad Neuronal y Cálculo Rápido",
      fr: "Vitesse Neuronale & Calcul Éclair",
      hi: "न्यूरल गति और त्वरित गणना",
      zh: "神经脉冲与心算极速竞技",
    },
    tagline: {
      ar: "سباق الإجابات الفورية والتركيز العالي مع عداد الكومبو والمضاعفات الصاعدة",
      en: "High-voltage mathematical duel with real-time combo multiplier streaks",
      es: "Duelo matemático de alto voltaje con rachas y multiplicadores en vivo",
      fr: "Duel mathématique survolté avec combos et multiplicateurs en direct",
      hi: "रीयल-टाइम कॉम्बो मल्टीप्लायर स्ट्रीक्स के साथ हाई-वोल्टेज गणितीय मुकाबला",
      zh: "高能毫秒级心算冲刺，连击加速音效与倍率爆发拉满肾上腺素",
    },
    soundMaterial: "glass",
    victoryInsignia: "lightning-bolt",
    countdownVibe: {
      ar: "شحن الخلايا العصبية مكتمل.. أطلق سرعة الحساب القصوى!",
      en: "Synapses supercharged.. Unleash maximum calculation speed!",
      es: "¡Sinapsis cargadas.. Desata la máxima velocidad de cálculo!",
      fr: "Synapses chargées.. Libérez votre vitesse maximale de calcul !",
      hi: "न्यूरॉन्स पूरी तरह चार्ज.. अधिकतम गति से गणना शुरू करें!",
      zh: "大脑突触瞬间超频.. 极速心算风暴轰然降临！",
    },
    turnPulseColor: "#06b6d4",
    palette: {
      primary: "#0e7490",
      accent: "#06b6d4",
      bg: "#050814",
      surface: "#091326",
      border: "rgba(6, 182, 212, 0.4)",
      glow: "rgba(6, 182, 212, 0.3)",
      text: "#ecfeff",
      cardGradient: "linear-gradient(145deg, rgba(6, 182, 212, 0.2) 0%, rgba(5, 8, 20, 0.95) 100%)",
      tableRim: "#164e63",
    },
    modes: {
      ai: {
        title: {
          ar: "تمرين عقلي سريع (منفرد)",
          en: "Mental Gym Solo Workout",
          es: "Entrenamiento Mental Solitario",
          fr: "Gym Cérébrale Solo",
          hi: "मानसिक कसरत एकल अभ्यास",
          zh: "神经心算健身房 (单人模式)",
        },
        desc: {
          ar: "اختبر سرعتك ودقتك في 10 أو 20 مسألة رياضية بدون أي مخاطرة",
          en: "Test your reflex velocity across 10 or 20 questions risk-free",
          es: "Pon a prueba tus reflejos en 10 o 20 preguntas sin riesgo",
          fr: "Testez votre vitesse de calcul sur 10 ou 20 questions sans risque",
          hi: "बिना किसी जोखिम के 10 या 20 प्रश्नों में अपनी गति का परीक्षण करें",
          zh: "零风险自测10题或20题极限心算反应力与准确率",
        },
        tag: {
          ar: "تمرين ذهني",
          en: "Brain Workout",
          es: "Gimnasio Mental",
          fr: "Gym Mentale",
          hi: "दिमागी कसरत",
          zh: "脑力拉练",
        },
        badge: {
          ar: "مجاني 100%",
          en: "Free Workout",
          es: "Gratis",
          fr: "Gratuit",
          hi: "मुफ़्त",
          zh: "完全免费",
        },
      },
      friend: {
        title: {
          ar: "سباق مباشر مع صديق",
          en: "Head-to-Head Friend Sprint",
          es: "Carrera Directa con un Amigo",
          fr: "Sprint Direct contre un Ami",
          hi: "दोस्त के साथ सीधी दौड़",
          zh: "好友连线毫秒心算对飙",
        },
        desc: {
          ar: "من يجيب أسرع؟ نافس صديقك مباشرة على نفس المسائل الرياضية",
          en: "Who solves faster? Challenge a friend with identical real-time math questions",
          es: "¿Quién resuelve más rápido? Compite en directo con las mismas preguntas",
          fr: "Qui calcule le plus vite ? Défiez un ami sur les mêmes questions en direct",
          hi: "कौन तेजी से हल करता है? समान प्रश्नों पर सीधे दोस्त से मुकाबला करें",
          zh: "同题毫秒级同屏竞答，胜负全凭纯粹手速与脑力",
        },
        tag: {
          ar: "تنافس فوري",
          en: "Real-Time Duel",
          es: "En Vivo",
          fr: "En Direct",
          hi: "रीयल-टाइम",
          zh: "同屏竞技",
        },
        badge: {
          ar: "تحدي خاص",
          en: "Private Match",
          es: "Privado",
          fr: "Privé",
          hi: "निजी",
          zh: "私享约战",
        },
      },
      match: {
        title: {
          ar: "ماراثون الحساب التنافسي (1 ضد 1)",
          en: "Ranked Speed Sprint (1v1)",
          es: "Sprint Clasificatorio de Cálculo",
          fr: "Sprint Classé de Calcul (1v1)",
          hi: "रैंक्ड स्पीड स्प्रिंट (1v1)",
          zh: "排位心算极速现金战 (1对1)",
        },
        desc: {
          ar: "توفيق فوري ضد عبقري بنفس مستواك والجوائز النقدية للفائز بالسرعة والدقة",
          en: "Instant matchmaking where superior accuracy and speed claim the pot",
          es: "Emparejamiento al instante donde la velocidad y precisión ganan",
          fr: "Matchmaking instantané où la rapidité et la précision emportent la mise",
          hi: "सटीकता और गति के आधार पर तुरंत मुकाबला और नकद पुरस्कार जीतें",
          zh: "秒级排位匹配同级心算强者，最高答对率与最快答题速度直接卷走奖池",
        },
        tag: {
          ar: "جوائز نقدية فورية",
          en: "Instant Cash Pot",
          es: "Bote en Efectivo",
          fr: "Gains Immédiats",
          hi: "त्वरित नकद पॉट",
          zh: "即时金币",
        },
        badge: {
          ar: "تنافسي ناري",
          en: "High Voltage",
          es: "Alto Voltaje",
          fr: "Haute Tension",
          hi: "उच्च वोल्टेज",
          zh: "高能对决",
        },
      },
      tournament: {
        title: {
          ar: "أولمبياد الحساب الذهني الخاطف",
          en: "Mental Math Olympiad Cup",
          es: "Olimpiada de Cálculo Mental",
          fr: "Olympiade de Calcul Mental",
          hi: "मानसिक गणित ओलंपियाड कप",
          zh: "极限心算奥林匹克争霸赛",
        },
        desc: {
          ar: "تصفيات إقصائية سريعة تجمع أسرع العقول على المنصة",
          en: "Single-elimination speed brackets crowning the fastest brain",
          es: "Cuadros eliminatorios veloces para coronar al cerebro más rápido",
          fr: "Tableaux éliminatoires rapides couronnant le cerveau le plus vif",
          hi: "सबसे तेज़ दिमाग को ताज पहनाने वाले नॉकआउट ब्रैकेट",
          zh: "全网神算快枪手汇聚，单淘汰争夺全平台最强极速脑王金杯",
        },
        tag: {
          ar: "أولمبياد المنصة",
          en: "Platform Olympiad",
          es: "Olimpiada",
          fr: "Olympiade",
          hi: "ओलंपियाड",
          zh: "全服盛典",
        },
        badge: {
          ar: "كأس العباقرة",
          en: "Genius Trophy",
          es: "Trofeo Genio",
          fr: "Trophée Génie",
          hi: "जीनियस ट्रॉफी",
          zh: "脑王金杯",
        },
      },
    },
  },

  xo: {
    gameId: "xo",
    persona: {
      ar: "شفرة الليزر والنزال الخاطف",
      en: "Neon Blade & Instant Reflex",
      es: "Hoja de Neón y Reflejo Puro",
      fr: "Lame Néon & Réflexes Purs",
      hi: "नियॉन ब्लेड और त्वरित चाल",
      zh: "霓虹光刃与闪电速战",
    },
    tagline: {
      ar: "نزال تيك-تاك-تو الخاطف بنظام سلسلة الجولات (الأفضل من 3 أو 5)",
      en: "High-tempo best-of series with razor-sharp neon grids and tactical traps",
      es: "Series al mejor de 3 o 5 con cuadrícula de neón y trampas tácticas",
      fr: "Séries au meilleur des 3 ou 5 avec grilles néon et pièges tactiques",
      hi: "सर्वश्रेष्ठ 3 या 5 श्रृंखला के साथ उच्च गति वाला नियॉन ग्रिड मुकाबला",
      zh: "高燃三局两胜/五局三胜制，霓虹交叉火力陷阱与闪电绝杀",
    },
    soundMaterial: "metal",
    victoryInsignia: "crossed-blades",
    countdownVibe: {
      ar: "شبكة الليزر تشتعل.. النزال الخاطف يبدأ!",
      en: "Laser grid ignited.. Instant blade duel begins!",
      es: "¡Cuadrícula láser encendida.. Comienza el duelo relámpago!",
      fr: "Grille laser allumée.. Le duel d'éclair commence !",
      hi: "लेजर ग्रिड सक्रिय.. त्वरित ब्लेड मुकाबला शुरू!",
      zh: "激光战网通电过载.. 闪电速斩对决即刻打响！",
    },
    turnPulseColor: "#38bdf8",
    palette: {
      primary: "#0284c7",
      accent: "#38bdf8",
      bg: "#07080d",
      surface: "#0c101a",
      border: "rgba(56, 189, 248, 0.35)",
      glow: "rgba(56, 189, 248, 0.25)",
      text: "#f0f9ff",
      cardGradient: "linear-gradient(145deg, rgba(56, 189, 248, 0.18) 0%, rgba(7, 8, 13, 0.95) 100%)",
      tableRim: "#0369a1",
    },
    modes: {
      ai: {
        title: {
          ar: "تدريب ضد البوت الذكي",
          en: "Practice vs Perfect Bot",
          es: "Práctica vs Bot Inteligente",
          fr: "Pratique contre Bot Intelligent",
          hi: "स्मार्ट बॉट के खिलाफ अभ्यास",
          zh: "与高能AI机甲极速练手",
        },
        desc: {
          ar: "تدرّب على كشف الفخاخ والتفرعات بدون أي مخاطرة مالية",
          en: "Sharpen tactical grid patterns and trap defense with zero risk",
          es: "Mejora la defensa de trampas y patrones de cuadrícula sin riesgo",
          fr: "Affûtez vos pièges et schémas tactiques sans risquer d'argent",
          hi: "शून्य जोखिम के साथ रणनीति और सुरक्षा का अभ्यास करें",
          zh: "零风险探查九宫格必胜分歧与防守死角",
        },
        tag: {
          ar: "تدريب مجاني",
          en: "Free Reflex",
          es: "Gratis",
          fr: "Gratuit",
          hi: "मुफ़्त",
          zh: "免费练刀",
        },
        badge: {
          ar: "بدون مخاطرة",
          en: "Zero Risk",
          es: "Sin Riesgo",
          fr: "Sans Risque",
          hi: "जोखिम रहित",
          zh: "零险演练",
        },
      },
      friend: {
        title: {
          ar: "مواجهة خاصة مع صديق",
          en: "Private Neon Showdown",
          es: "Duelo Privado de Neón",
          fr: "Confrontation Privée Néon",
          hi: "दोस्त के साथ निजी नियॉन मुकाबला",
          zh: "好友私密霓虹光刃切磋",
        },
        desc: {
          ar: "اختر سلسلة الجولات (Best of 3 أو 5) وأرسل الرابط مباشرة",
          en: "Set Best of 3 or 5 series and send direct room invite",
          es: "Elige serie al mejor de 3 o 5 e invita con enlace directo",
          fr: "Définissez une série au meilleur des 3 ou 5 et invitez par lien",
          hi: "सर्वश्रेष्ठ 3 या 5 श्रृंखला चुनें और सीधा लिंक भेजें",
          zh: "自定三局两胜或五局三胜制，生成私有链接直面好友",
        },
        tag: {
          ar: "سلسلة جولات",
          en: "Series Format",
          es: "Serie a Rondas",
          fr: "Format Série",
          hi: "सीरीज़ प्रारूप",
          zh: "系列赛制",
        },
        badge: {
          ar: "رابط خاص",
          en: "Direct Link",
          es: "Enlace Directo",
          fr: "Lien Direct",
          hi: "सीधा लिंक",
          zh: "直约私房",
        },
      },
      match: {
        title: {
          ar: "نزال السرعة التنافسي (1 ضد 1)",
          en: "Ranked Razor Duel (1v1)",
          es: "Duelo Rápido Clasificatorio",
          fr: "Duel Éclair Classé (1v1)",
          hi: "रैंक्ड त्वरित मुकाबला (1v1)",
          zh: "排位闪电速决金币对局 (1对1)",
        },
        desc: {
          ar: "مبارزة خاطفة بجوائز نقدية فورية بدون أي تأخير",
          en: "Lightning fast duel with immediate real-money prize payout",
          es: "Duelo ultrarrápido con premio en efectivo al instante",
          fr: "Duel ultra-rapide avec paiement immédiat en cash",
          hi: "तत्काल वास्तविक नकद पुरस्कार के साथ बिजली जैसा तेज़ मुकाबला",
          zh: "毫秒级胜负即决，绝无拖泥带水，胜者直接揽入奖池",
        },
        tag: {
          ar: "جوائز فورية",
          en: "Instant Payout",
          es: "Pago Rápido",
          fr: "Paiement Rapide",
          hi: "त्वरित भुगतान",
          zh: "秒结秒付",
        },
        badge: {
          ar: "خاطف وسريع",
          en: "High Speed",
          es: "Alta Velocidad",
          fr: "Haute Vitesse",
          hi: "तेज़ गति",
          zh: "闪电排位",
        },
      },
      tournament: {
        title: {
          ar: "بطولة الشفرة الخاطفة",
          en: "Neon Blade Knockout Cup",
          es: "Copa de la Hoja de Neón",
          fr: "Coupe de la Lame Néon",
          hi: "नियॉन ब्लेड नॉकआउट कप",
          zh: "光刃极速单败巅峰杯",
        },
        desc: {
          ar: "مباريات إقصائية سريعة بجوائز تصاعدية لكل دور",
          en: "Rapid-fire knockout rounds with escalating prize pools",
          es: "Rondas eliminatorias ultrarrápidas con premios crecientes",
          fr: "Tours éliminatoires ultra-rapides avec cagnottes croissantes",
          hi: "बढ़ते पुरस्कारों के साथ तेज़ नॉकआउट राउंड",
          zh: "快节奏单败淘汰连环对决，层层闯关赢取累积奖池",
        },
        tag: {
          ar: "أدوار تصاعدية",
          en: "Escalating Rounds",
          es: "Premios Crecientes",
          fr: "Prix Croissants",
          hi: "बढ़ते राउंड",
          zh: "层级晋级",
        },
        badge: {
          ar: "كأس السرعة",
          en: "Speed Cup",
          es: "Copa Velocidad",
          fr: "Coupe Vitesse",
          hi: "स्पीड कप",
          zh: "极速奖杯",
        },
      },
    },
  },

  "connect-four": {
    gameId: "connect-four",
    persona: {
      ar: "كمين الأعمدة والأقراص الأربعة",
      en: "Arcade Gravity Matrix",
      es: "Matriz de Gravedad y Cuatro en Línea",
      fr: "Matrice Gravité & Puissance 4",
      hi: "ग्रेविटी मैट्रिक्स और चार पंक्तियां",
      zh: "重力纵向机甲四连珠",
    },
    tagline: {
      ar: "سقوط الأقراص الرأسي والمصائد التكتيكية ذات الاتجاهين",
      en: "Vertical drop mechanics with dual-threat traps and diagonal alignments",
      es: "Mecánica de caída vertical con trampas diagonales de doble amenaza",
      fr: "Mécanique de chute verticale avec pièges diagonaux à double menace",
      hi: "दोहरे खतरे वाले जालों और विकर्ण संरेखण के साथ वर्टिकल ड्रॉप तंत्र",
      zh: "纵向重力落子深度博弈，双头绞杀与对角线绝杀战法",
    },
    soundMaterial: "ceramic",
    victoryInsignia: "quad-circle",
    countdownVibe: {
      ar: "أعمدة الجاذبية تفتح مساراتها.. الأقراص جاهزة للهبوط!",
      en: "Gravity columns unlocked.. Tokens primed for vertical drop!",
      es: "¡Columnas desbloqueadas.. Fichas listas para caer!",
      fr: "Colonnes déverrouillées.. Jetons prêts pour la chute !",
      hi: "कॉलम अनलॉक.. गोटियां गिरने के लिए तैयार!",
      zh: "重力滑槽闸门就绪.. 战术圆盘轰然落轨！",
    },
    turnPulseColor: "#0284c7",
    palette: {
      primary: "#0369a1",
      accent: "#38bdf8",
      bg: "#070e1c",
      surface: "#0c1a33",
      border: "rgba(2, 132, 199, 0.35)",
      glow: "rgba(2, 132, 199, 0.25)",
      text: "#f0f9ff",
      cardGradient: "linear-gradient(145deg, rgba(2, 132, 199, 0.2) 0%, rgba(7, 14, 28, 0.95) 100%)",
      tableRim: "#075985",
    },
    modes: {
      ai: {
        title: {
          ar: "تحدي روبوت الأعمدة الذكي",
          en: "Practice vs Column AI",
          es: "Práctica vs IA de Columnas",
          fr: "Pratique contre IA de Colonnes",
          hi: "कॉलम एआई के खिलाफ अभ्यास",
          zh: "四子棋重力机甲人机特训",
        },
        desc: {
          ar: "تدرّب على قراءة التهديدات المزدوجة والفخاخ الرأسية",
          en: "Master vertical traps and diagonal forks with zero financial risk",
          es: "Domina las trampas verticales y diagonales sin riesgo financiero",
          fr: "Maîtrisez les pièges verticaux et fourchettes sans risque",
          hi: "बिना किसी वित्तीय जोखिम के रणनीतिक चालों का अभ्यास करें",
          zh: "零风险操练双杀必胜陷阱与对角线封杀战术",
        },
        tag: {
          ar: "تدريب تكتيكي",
          en: "Tactical Training",
          es: "Entrenamiento",
          fr: "Entraînement",
          hi: "प्रशिक्षण",
          zh: "战术操练",
        },
        badge: {
          ar: "مجاني",
          en: "Free",
          es: "Gratis",
          fr: "Gratuit",
          hi: "मुफ़्त",
          zh: "免费演训",
        },
      },
      friend: {
        title: {
          ar: "نزال الأعمدة مع صديق",
          en: "Private Gravity Duel",
          es: "Duelo Privado de Gravedad",
          fr: "Duel Privé de Gravité",
          hi: "दोस्त के साथ निजी ग्रेविटी मैच",
          zh: "好友重力矩阵四连战",
        },
        desc: {
          ar: "اختر الأفضل من 3 أو 5 جولات وتحدَّ صديقك برابط خاص",
          en: "Choose Best of 3 or 5 format and challenge your friend directly",
          es: "Elige formato al mejor de 3 o 5 e invita a un amigo",
          fr: "Choisissez le format au meilleur des 3 ou 5 et invitez un ami",
          hi: "सर्वश्रेष्ठ 3 या 5 प्रारूप चुनें और सीधे दोस्त को आमंत्रित करें",
          zh: "定制多局多胜长盘制，直接把链接扔给好友展开切磋",
        },
        tag: {
          ar: "سلسلة مواجهات",
          en: "Multi-Round",
          es: "Múltiples Rondas",
          fr: "Plusieurs Tours",
          hi: "मल्टी-राउंड",
          zh: "多轮决胜",
        },
        badge: {
          ar: "دعوة خاصة",
          en: "Direct Link",
          es: "Enlace Directo",
          fr: "Lien Direct",
          hi: "सीधा लिंक",
          zh: "专属直约",
        },
      },
      match: {
        title: {
          ar: "نزال الأربعة التنافسي (1 ضد 1)",
          en: "Ranked Connect Duel (1v1)",
          es: "Duelo Clasificatorio de Cuatro",
          fr: "Duel Classé Puissance 4 (1v1)",
          hi: "रैंक्ड कनेक्ट मुकाबला (1v1)",
          zh: "天梯排位重力四子金币战 (1对1)",
        },
        desc: {
          ar: "توفيق فوري سريع بجوائز نقدية لأول من يكمل الرباعية",
          en: "Fast-paced real-money duel where the first to connect 4 wins the pot",
          es: "Duelo rápido por dinero donde el primero en conectar 4 gana",
          fr: "Duel rapide avec enjeu où le premier à aligner 4 jetons l'emporte",
          hi: "तेज़ गति वाला नकद मुकाबला जहाँ पहले 4 जोड़ने वाला जीतता है",
          zh: "排位极速匹配，率先连通四枚同色圆盘即刻锁定胜局揽金",
        },
        tag: {
          ar: "أرباح فورية",
          en: "Instant Win",
          es: "Ganancia Rápida",
          fr: "Gain Immédiat",
          hi: "तत्काल जीत",
          zh: "连珠即胜",
        },
        badge: {
          ar: "تنافسي",
          en: "Ranked",
          es: "Clasificatorio",
          fr: "Classé",
          hi: "रैंक्ड",
          zh: "天梯排位",
        },
      },
      tournament: {
        title: {
          ar: "كأس أبطال الأعمدة الرباعية",
          en: "Connect Four Champions Cup",
          es: "Copa de Campeones de Cuatro en Línea",
          fr: "Coupe des Champions Puissance 4",
          hi: "कनेक्ट फोर चैंपियंस कप",
          zh: "重力四子连珠大师冠军杯",
        },
        desc: {
          ar: "سلسلة أدوار إقصائية يتنافس فيها أمهر دهاة التكتيك",
          en: "Single-elimination championship featuring tactical column strategists",
          es: "Campeonato eliminatorio con estrategas tácticos de columnas",
          fr: "Championnat à élimination directe réunissant les maîtres stratèges",
          hi: "रणनीतिक खिलाड़ियों के साथ सिंगल-एलिमिनेशन चैम्पियनशिप",
          zh: "全网纵横大师云集，单败阶梯淘汰决战紫禁之巅",
        },
        tag: {
          ar: "كأس البطولة",
          en: "Championship",
          es: "Campeonato",
          fr: "Championnat",
          hi: "चैम्पियनशिप",
          zh: "锦标大奖",
        },
        badge: {
          ar: "جوائز كبرى",
          en: "Major Pot",
          es: "Gran Premio",
          fr: "Gros Lot",
          hi: "बड़ा पुरस्कार",
          zh: "丰厚奖池",
        },
      },
    },
  },

  checkers: {
    gameId: "checkers",
    persona: {
      ar: "معركة الدامة وتتويج الملوك",
      en: "Tactical Damas & Dark Slate",
      es: "Damas Tácticas y Reyes Coronados",
      fr: "Dames Tactiques & Rois Couronnés",
      hi: "रणनीतिक चेकर्स और राजा का राज्याभिषेक",
      zh: "战术跳棋与棋王加冕风暴",
    },
    tagline: {
      ar: "القفز الإجباري والتتويج الملكي بسلاسل الأكل المتتالي الملحمية",
      en: "Mandatory multi-jump capture chains and royal king crowning maneuvers",
      es: "Cadenas de captura múltiple obligatoria y coronación de reyes",
      fr: "Prises obligatoires en chaîne et couronnement de rois royaux",
      hi: "अनिवार्य बहु-कूद श्रृंखला और शाही राजा का राज्याभिषेक",
      zh: "硬核强制连跳吃子连击，底线冲刺王者加冕全盘横扫",
    },
    soundMaterial: "wood",
    victoryInsignia: "king-blade",
    countdownVibe: {
      ar: "الأقراص تصطف على المربعات الداكنة.. المعركة تنطلق!",
      en: "Checkers locked on dark tiles.. Tactical conquest begins!",
      es: "¡Fichas alineadas en casillas oscuras.. Inicia la conquista!",
      fr: "Pions verrouillés sur cases sombres.. La conquête commence !",
      hi: "काले वर्गों पर मोहरे तैयार.. रणनीतिक विजय शुरू!",
      zh: "重装棋子暗格落座.. 全盘连跳征服之战轰然打响！",
    },
    turnPulseColor: "#dc2626",
    palette: {
      primary: "#991b1b",
      accent: "#ef4444",
      bg: "#0c0d12",
      surface: "#181922",
      border: "rgba(239, 68, 68, 0.35)",
      glow: "rgba(239, 68, 68, 0.22)",
      text: "#fef2f2",
      cardGradient: "linear-gradient(145deg, rgba(239, 68, 68, 0.18) 0%, rgba(12, 13, 18, 0.95) 100%)",
      tableRim: "#450a0a",
    },
    modes: {
      ai: {
        title: {
          ar: "تمرين الدامة مع البوت",
          en: "Practice vs Checkers AI",
          es: "Práctica vs IA de Damas",
          fr: "Pratique contre l'IA de Dames",
          hi: "चेकर्स एआई के खिलाफ अभ्यास",
          zh: "国际跳棋机甲对练",
        },
        desc: {
          ar: "تدرّب على قراءة سلاسل القفز الإجباري وتأمين التتويج",
          en: "Master mandatory jump patterns and king defense risk-free",
          es: "Domina las cadenas de captura y defensa de reyes sin riesgo",
          fr: "Maîtrisez les prises en chaîne et la défense du roi sans risque",
          hi: "बिना जोखिम के अनिवार्य कूद और राजा की रक्षा का अभ्यास करें",
          zh: "零风险磨练底线升王步法与迫伏吃子连击",
        },
        tag: {
          ar: "تدريب تكتيكي",
          en: "Tactical Drill",
          es: "Práctica",
          fr: "Pratique",
          hi: "अभ्यास",
          zh: "战术推演",
        },
        badge: {
          ar: "مجاني",
          en: "Free",
          es: "Gratis",
          fr: "Gratuit",
          hi: "मुफ़्त",
          zh: "免费练习",
        },
      },
      friend: {
        title: {
          ar: "تحدي الدامة الخاص",
          en: "Private Checkers Board",
          es: "Tablero Privado de Damas",
          fr: "Plateau Privé de Dames",
          hi: "निजी चेकर्स बोर्ड",
          zh: "好友私密跳棋战局",
        },
        desc: {
          ar: "أرسل رابط التحدي لصديقك والعبا بقواعد الدامة الصارمة",
          en: "Send a direct room invite for a classic 1v1 checkers battle",
          es: "Invita a un amigo a un duelo clásico de damas por enlace",
          fr: "Invitez un ami pour un duel classique de dames via lien direct",
          hi: "क्लासिक 1v1 चेकर्स मुकाबले के लिए सीधे लिंक से आमंत्रित करें",
          zh: "生成专属房间直链，与好友依循经典国际跳棋规则对决",
        },
        tag: {
          ar: "نزال أصدقاء",
          en: "Friend Duel",
          es: "Amigos",
          fr: "Amis",
          hi: "मित्र",
          zh: "好友约战",
        },
        badge: {
          ar: "رابط خاص",
          en: "Direct Link",
          es: "Enlace Directo",
          fr: "Lien Direct",
          hi: "सीधा लिंक",
          zh: "专属链接",
        },
      },
      match: {
        title: {
          ar: "نزال الدامة التنافسي (1 ضد 1)",
          en: "Ranked Checkers Duel (1v1)",
          es: "Duelo Clasificatorio de Damas",
          fr: "Duel Classé de Dames (1v1)",
          hi: "रैंक्ड चेकर्स मुकाबला (1v1)",
          zh: "天梯排位跳棋金币战 (1对1)",
        },
        desc: {
          ar: "توفيق فوري ضد لاعب حقيقي مع أرباح نقدية لمن يبيد أقراص الخصم",
          en: "Real-money duel where capturing or trapping all opponent pieces wins",
          es: "Duelo por dinero donde capturar o bloquear todas las fichas gana",
          fr: "Duel pour de l'argent réel où bloquer ou capturer tout l'adversaire gagne",
          hi: "वास्तविक नकद मुकाबला जहाँ प्रतिद्वंद्वी की सभी गोटियों को फंसाने वाला जीतता है",
          zh: "排位秒配对手，吃尽或锁死敌方全部棋子者全额斩获现金奖金",
        },
        tag: {
          ar: "جوائز نقدية",
          en: "Cash Prize",
          es: "Premio en Efectivo",
          fr: "Prix en Cash",
          hi: "नकद पुरस्कार",
          zh: "现金结算",
        },
        badge: {
          ar: "تنافسي",
          en: "Ranked",
          es: "Clasificatorio",
          fr: "Classé",
          hi: "रैंक्ड",
          zh: "天梯竞技",
        },
      },
      tournament: {
        title: {
          ar: "بطولة ملوك الدامة الكبرى",
          en: "Checkers Kings Invitational",
          es: "Torneo de Reyes de Damas",
          fr: "Tournoi des Rois de Dames",
          hi: "चेकर्स किंग्स टूर्नामेंट",
          zh: "国际跳棋棋王邀请赛",
        },
        desc: {
          ar: "سلسلة أدوار إقصائية لتتويج البطل المطلق في لعبة الدامة",
          en: "Grand championship brackets testing endurance and crowning the master",
          es: "Gran campeonato eliminatorio que corona al maestro absoluto de damas",
          fr: "Grand championnat à élimination couronnant le grand maître des dames",
          hi: "भव्य चैम्पियनशिप जो सर्वश्रेष्ठ चेकर्स मास्टर को ताज पहनाती है",
          zh: "全网高手同台打响单败淘汰赛，问鼎唯一棋王桂冠",
        },
        tag: {
          ar: "كأس البطولة",
          en: "Grand Cup",
          es: "Gran Copa",
          fr: "Grand Trophée",
          hi: "भव्य कप",
          zh: "王者锦标",
        },
        badge: {
          ar: "جوائز مجمعة",
          en: "Big Pool",
          es: "Gran Bote",
          fr: "Grande Cagnotte",
          hi: "बड़ा पूल",
          zh: "大奖池",
        },
      },
    },
  },

  reversi: {
    gameId: "reversi",
    persona: {
      ar: "قلب الموازين والهيمنة المطلقة",
      en: "The Emerald Flip & Reversal",
      es: "El Giro Esmeralda y Dominio Total",
      fr: "Retournement Émeraude & Contrôle",
      hi: "एमराल्ड फ्लिप और पूर्ण प्रभुत्व",
      zh: "黑白翻转与领地逆袭狂潮",
    },
    tagline: {
      ar: "شلال انقلاب الأقراص واقتناص الزوايا الأربع للسيطرة على كامل الرقعة",
      en: "Cascade disc flips, corner traps, and sudden territory reversals",
      es: "Cascadas de volteo de fichas, esquinas clave y giros repentinos",
      fr: "Cascades de retournements, contrôle des coins et revirements soudains",
      hi: "डिस्क का कैस्केड फ्लिप, कोनों का नियंत्रण और अप्रत्याशित उलटफेर",
      zh: "连环黑白翻转波浪，夺占四角金边稳固胜局，终盘大逆转",
    },
    soundMaterial: "ceramic",
    victoryInsignia: "yin-yang",
    countdownVibe: {
      ar: "الأقراص الأربعة المركزية مستقرة.. شلال الدوران يبدأ!",
      en: "Central discs locked in place.. Cascade flip wave commences!",
      es: "¡Fichas centrales fijadas.. Inicia la ola de volteos!",
      fr: "Jetons centraux en place.. La vague de retournements commence !",
      hi: "केंद्रीय डिस्क सेट.. कैस्केड फ्लिप लहर शुरू!",
      zh: "中央四子定盘结界.. 黑白翻转狂涛骤然升腾！",
    },
    turnPulseColor: "#10b981",
    palette: {
      primary: "#064e3b",
      accent: "#10b981",
      bg: "#05140f",
      surface: "#0c281e",
      border: "rgba(16, 185, 129, 0.35)",
      glow: "rgba(16, 185, 129, 0.22)",
      text: "#ecfdf5",
      cardGradient: "linear-gradient(145deg, rgba(16, 185, 129, 0.18) 0%, rgba(5, 20, 15, 0.95) 100%)",
      tableRim: "#047857",
    },
    modes: {
      ai: {
        title: {
          ar: "تمرين ريفيرسي مع الروبوت",
          en: "Practice vs Reversi AI",
          es: "Práctica vs IA de Reversi",
          fr: "Pratique contre l'IA Reversi",
          hi: "रिवर्सि एआई के खिलाफ अभ्यास",
          zh: "黑白棋人机推演演练",
        },
        desc: {
          ar: "تدرّب على السيطرة على الزوايا والحواف وتجنب الفخاخ",
          en: "Master corner control and disc mobility with zero risk",
          es: "Domina el control de esquinas y movilidad sin riesgo",
          fr: "Maîtrisez le contrôle des coins et la mobilité sans risque",
          hi: "बिना जोखिम के कोनों के नियंत्रण और गतिशीलता का अभ्यास करें",
          zh: "零风险钻研角格控制、外边占位与行动步数封锁",
        },
        tag: {
          ar: "تكتيك الزوايا",
          en: "Corner Tactics",
          es: "Táctica de Esquinas",
          fr: "Tactique des Coins",
          hi: "कोने की रणनीति",
          zh: "角格战术",
        },
        badge: {
          ar: "مجاني",
          en: "Free",
          es: "Gratis",
          fr: "Gratuit",
          hi: "मुफ़्त",
          zh: "免费练习",
        },
      },
      friend: {
        title: {
          ar: "مواجهة ريفيرسي مع صديق",
          en: "Private Reversi Board",
          es: "Tablero Privado de Reversi",
          fr: "Plateau Privé de Reversi",
          hi: "दोस्त के साथ निजी रिवर्सि",
          zh: "好友私密黑白棋对弈",
        },
        desc: {
          ar: "شارك رابط الغرفة مباشرة وتنافسا في قلب الأقراص",
          en: "Send a direct room invite to test strategic territory flips with a friend",
          es: "Invita a un amigo y compite volteando fichas por el tablero",
          fr: "Invitez un ami et disputez-vous le contrôle du plateau",
          hi: "सीधे लिंक से आमंत्रित करें और बोर्ड पर गोटियां पलटें",
          zh: "专属链接直邀好友，方寸绿呢棋盘上演黑白交替争锋",
        },
        tag: {
          ar: "تحدي الأصدقاء",
          en: "Friend Challenge",
          es: "Amigos",
          fr: "Amis",
          hi: "मित्र चुनौती",
          zh: "双人约战",
        },
        badge: {
          ar: "رابط مباشر",
          en: "Direct Link",
          es: "Enlace Directo",
          fr: "Lien Direct",
          hi: "सीधा लिंक",
          zh: "直约私房",
        },
      },
      match: {
        title: {
          ar: "نزال ريفيرسي التنافسي (1 ضد 1)",
          en: "Ranked Reversi Duel (1v1)",
          es: "Duelo Clasificatorio de Reversi",
          fr: "Duel Classé de Reversi (1v1)",
          hi: "रैंक्ड रिवर्सि मुकाबला (1v1)",
          zh: "天梯排位黑白棋现金战 (1对1)",
        },
        desc: {
          ar: "توفيق فوري والجوائز النقدية لصاحب الأكثرية في الأقراص عند نهاية اللوح",
          en: "Real-money duel where the player with the most flipped discs wins the pot",
          es: "Duelo por dinero donde quien tenga más fichas volteadas gana el bote",
          fr: "Duel avec enjeu où celui qui a le plus de jetons emporte la cagnotte",
          hi: "वास्तविक नकद मुकाबला जहाँ सबसे अधिक डिस्क पलटने वाला जीतता है",
          zh: "极速匹配同段位棋士，满盘结算时拥有多数颜色棋子者独享奖池",
        },
        tag: {
          ar: "جوائز فورية",
          en: "Instant Win",
          es: "Ganancia Rápida",
          fr: "Gain Immédiat",
          hi: "तत्काल जीत",
          zh: "满盘即胜",
        },
        badge: {
          ar: "تنافسي",
          en: "Ranked",
          es: "Clasificatorio",
          fr: "Classé",
          hi: "रैंक्ड",
          zh: "排位排号",
        },
      },
      tournament: {
        title: {
          ar: "بطولة أساتذة الريفيرسي",
          en: "Reversi Grandmaster Cup",
          es: "Copa Gran Maestro de Reversi",
          fr: "Coupe Grand Maître de Reversi",
          hi: "रिवर्सि ग्रैंडमास्टर कप",
          zh: "黑白棋宗师大师杯",
        },
        desc: {
          ar: "أدوار خروج المغلوب لتتويج خبير الهيمنة وقلب الموازين",
          en: "Single-elimination brackets identifying the true master of disc control",
          es: "Cuadros de eliminación directa que coronan al auténtico maestro de fichas",
          fr: "Tableaux éliminatoires désignant le véritable maître du contrôle",
          hi: "सच्चे रिवर्सि मास्टर को ताज पहनाने वाले नॉकआउट ब्रैकेट",
          zh: "单败淘汰阶梯大决战，层层翻转角逐黑白领地至尊王座",
        },
        tag: {
          ar: "كأس البطولة",
          en: "Championship",
          es: "Campeonato",
          fr: "Championnat",
          hi: "चैम्पियनशिप",
          zh: "锦标大奖",
        },
        badge: {
          ar: "جوائز كبرى",
          en: "Big Pot",
          es: "Gran Bote",
          fr: "Grande Cagnotte",
          hi: "बड़ा पॉट",
          zh: "丰厚奖赏",
        },
      },
    },
  },

  gomoku: {
    gameId: "gomoku",
    persona: {
      ar: "زن الأحجار والخمسة المتصلة",
      en: "Zen Wood & The Five Stones",
      es: "Zen de Madera y Cinco en Línea",
      fr: "Zen du Bois & Les Cinq Pierres",
      hi: "ज़ेन लकड़ी और पांच पत्थर",
      zh: "纹枰榧木与五子连珠之道",
    },
    tagline: {
      ar: "هدوء وتأمل وضربات خاطفة.. أول من يصل إلى خمسة أحجار متصلة ينتصر فوراً",
      en: "Meditative focus meeting sudden tactical death: first to align 5 stones wins",
      es: "Enfoque meditativo y muerte súbita táctica: el primero en alinear 5 gana",
      fr: "Concentration méditative et mort subite : le premier à aligner 5 gagne",
      hi: "ध्यान और त्वरित रणनीति: पहले 5 पत्थर संरेखित करने वाला जीतता है",
      zh: "榧木棋盘清脆落子，静若处子动若惊雷，先成五子者一击定乾坤",
    },
    soundMaterial: "wood",
    victoryInsignia: "zen-stone",
    countdownVibe: {
      ar: "لوح الخشب الطبيعي مهيّأ.. الحجر الأول ينتظر وضعه!",
      en: "Natural kaya board cleared.. First stone awaits placement!",
      es: "¡Tablero de madera despejado.. La primera piedra espera!",
      fr: "Plateau de bois prêt.. La première pierre attend d'être posée !",
      hi: "प्राकृतिक लकड़ी का बोर्ड तैयार.. पहला पत्थर रखे जाने की प्रतीक्षा में!",
      zh: "原生榧木棋盘净空入局.. 首枚黑石落子在即！",
    },
    turnPulseColor: "#c29b38",
    palette: {
      primary: "#78350f",
      accent: "#c29b38",
      bg: "#100d0a",
      surface: "#1f1812",
      border: "rgba(194, 155, 56, 0.35)",
      glow: "rgba(194, 155, 56, 0.22)",
      text: "#fdf8ee",
      cardGradient: "linear-gradient(145deg, rgba(194, 155, 56, 0.18) 0%, rgba(16, 13, 10, 0.95) 100%)",
      tableRim: "#451a03",
    },
    modes: {
      ai: {
        title: {
          ar: "تمرين غوموكو التأملي (بوت)",
          en: "Zen Practice vs AI",
          es: "Práctica Zen vs IA",
          fr: "Pratique Zen contre l'IA",
          hi: "एआई के खिलाफ ज़ेन अभ्यास",
          zh: "五子连珠静心人机推演",
        },
        desc: {
          ar: "تدرّب على قراءة التهديدات المتعامدة وبناء الفخاخ بدون مخاطرة",
          en: "Sharpen open-four traps and three-in-a-row forks with zero risk",
          es: "Entrena ataques abiertos y dobles amenazas de tres sin riesgo",
          fr: "Affûtez vos attaques ouvertes et menaces de trois sans risque",
          hi: "बिना किसी जोखिम के खुली चालों और दोहरे खतरों का अभ्यास करें",
          zh: "零风险参悟活三成四、双杀陷阱与先手防守死活",
        },
        tag: {
          ar: "تركيز وتأمل",
          en: "Zen Focus",
          es: "Enfoque Zen",
          fr: "Focus Zen",
          hi: "ज़ेन फोकस",
          zh: "禅意凝神",
        },
        badge: {
          ar: "مجاني",
          en: "Free",
          es: "Gratis",
          fr: "Gratuit",
          hi: "मुफ़्त",
          zh: "免费研习",
        },
      },
      friend: {
        title: {
          ar: "مبارزة غوموكو خاصة",
          en: "Private Zen Stone Match",
          es: "Partida Zen Privada",
          fr: "Match Zen Privé",
          hi: "निजी ज़ेन स्टोन मैच",
          zh: "好友私密五子棋局",
        },
        desc: {
          ar: "تحدَّ صديقك برابط مباشر على لوح الخشب الطبيعي 15×15",
          en: "Direct room invite for an authentic 15x15 Goban stone duel",
          es: "Invita con enlace directo para un duelo auténtico de piedras 15x15",
          fr: "Invitation par lien direct pour un duel de pierres authentique 15x15",
          hi: "प्रामाणिक 15x15 गोबैन स्टोन मुकाबले के लिए सीधे लिंक से आमंत्रित करें",
          zh: "一键发送邀请直链，在15×15正规格盘上与好友品茗对决",
        },
        tag: {
          ar: "لوح 15×15",
          en: "15x15 Board",
          es: "Tablero 15x15",
          fr: "Plateau 15x15",
          hi: "15x15 बोर्ड",
          zh: "15×15正格",
        },
        badge: {
          ar: "رابط خاص",
          en: "Direct Link",
          es: "Enlace Directo",
          fr: "Lien Direct",
          hi: "सीधा लिंक",
          zh: "专属链接",
        },
      },
      match: {
        title: {
          ar: "نزال الخمسة التنافسي (1 ضد 1)",
          en: "Ranked Five-in-a-Row (1v1)",
          es: "Duelo Clasificatorio Cinco en Línea",
          fr: "Duel Classé Cinq en Ligne (1v1)",
          hi: "रैंक्ड फाइव-इन-ए-रो (1v1)",
          zh: "天梯排位五子速决金币战 (1对1)",
        },
        desc: {
          ar: "توفيق فوري سريع وأرباح نقدية لمن يربط 5 أحجار متصلة أولاً",
          en: "Real-money duel where connecting 5 stones claims the pot instantly",
          es: "Duelo por dinero donde conectar 5 piedras gana el bote al instante",
          fr: "Duel avec enjeu où aligner 5 pierres emporte le pot immédiatement",
          hi: "वास्तविक नकद मुकाबला जहाँ 5 पत्थर जोड़ने पर तुरंत जीत मिलती है",
          zh: "排位极速秒配，率先完成五子连星即刻绝杀揽金",
        },
        tag: {
          ar: "فوز قاضٍ فوري",
          en: "Instant Win",
          es: "Victoria Instantánea",
          fr: "Victoire Immédiate",
          hi: "त्वरित जीत",
          zh: "五子即胜",
        },
        badge: {
          ar: "تنافسي",
          en: "Ranked",
          es: "Clasificatorio",
          fr: "Classé",
          hi: "रैंक्ड",
          zh: "天梯决战",
        },
      },
      tournament: {
        title: {
          ar: "كأس زن وأساتذة الغوموكو",
          en: "Gomoku Zen Masters Cup",
          es: "Copa Maestros Zen de Gomoku",
          fr: "Coupe des Maîtres Zen de Gomoku",
          hi: "गोमोकू ज़ेन मास्टर्स कप",
          zh: "五子连珠宗师巅峰杯",
        },
        desc: {
          ar: "بطولة إقصائية كبرى تجمع أصحاب النظرة التكتيكية الثاقبة",
          en: "Championship brackets featuring sudden-death five-in-a-row masters",
          es: "Torneo eliminatorio con maestros del cinco en línea a muerte súbita",
          fr: "Tournoi à élimination directe réunissant les maîtres du cinq en ligne",
          hi: "अचानक मौत वाले फाइव-इन-ए-रो मास्टर्स का चैम्पियनशिप ब्रैकेट",
          zh: "全网顶尖五子棋国手单败突击连战，问鼎宗师金杯",
        },
        tag: {
          ar: "كأس البطولة",
          en: "Grand Cup",
          es: "Gran Copa",
          fr: "Grand Trophée",
          hi: "भव्य कप",
          zh: "至尊杯赛",
        },
        badge: {
          ar: "جوائز كبرى",
          en: "Big Pool",
          es: "Gran Bote",
          fr: "Grande Cagnotte",
          hi: "बड़ा पूल",
          zh: "丰厚奖池",
        },
      },
    },
  },

  seega: {
    gameId: "seega",
    persona: {
      ar: "حرب الرمال وأحجار الفراعنة",
      en: "Egyptian Sandstone & Nile Tactics",
      es: "Arenisca Egipcia y Táctica del Nilo",
      fr: "Grès Égyptien & Tactique du Nil",
      hi: "मिस्र के बलुआ पत्थर और नील रणनीति",
      zh: "尼罗古沙与法老玄石棋战",
    },
    tagline: {
      ar: "أعرق ألعاب وادي النيل: مرحلة التموضع الحر ثم الإطباق وحصر أحجار الخصم",
      en: "Ancient Nile strategic duel: placement phase followed by relentless enclosure",
      es: "Duelo estratégico del antiguo Nilo: fase de colocación y asedio",
      fr: "Duel stratégique de l'Égypte ancienne : phase de pose puis encerclement",
      hi: "प्राचीन नील नदी की रणनीतिक लड़ाई: स्थान निर्धारण और फिर घेराबंदी",
      zh: "源自尼罗河谷的古老战术：双阶段自由布子与围剿截杀",
    },
    soundMaterial: "ceramic",
    victoryInsignia: "scarab",
    countdownVibe: {
      ar: "رمال وادي النيل تستقر.. الأحقاف مستعدة لأحجار الفراعنة!",
      en: "Nile sands settle.. The sandstone board awakens!",
      es: "¡Las arenas del Nilo se asientan.. El tablero despierta!",
      fr: "Les sables du Nil se posent.. Le plateau s'éveille !",
      hi: "नील नदी की रेत शांत.. बलुआ पत्थर का बोर्ड जागता है!",
      zh: "尼罗古沙沉寂定格.. 法老玄石棋盘已然苏醒！",
    },
    turnPulseColor: "#d97706",
    palette: {
      primary: "#92400e",
      accent: "#d97706",
      bg: "#130d07",
      surface: "#24180e",
      border: "rgba(217, 119, 6, 0.35)",
      glow: "rgba(217, 119, 6, 0.22)",
      text: "#fef3c7",
      cardGradient: "linear-gradient(145deg, rgba(217, 119, 6, 0.2) 0%, rgba(19, 13, 7, 0.95) 100%)",
      tableRim: "#451a03",
    },
    modes: {
      ai: {
        title: {
          ar: "تمرين سيجة مع البوت",
          en: "Practice vs Seega AI",
          es: "Práctica vs IA de Seega",
          fr: "Pratique contre l'IA Seega",
          hi: "सीगा एआई के खिलाफ अभ्यास",
          zh: "法老玄石机甲对战研习",
        },
        desc: {
          ar: "تدرّب على مرحلة النشر الذكي وتجنب فخ الحصر في المنتصف",
          en: "Master optimal initial placement and central sanctuary traps risk-free",
          es: "Domina la colocación inicial y trampas del santuario central sin riesgo",
          fr: "Maîtrisez la pose initiale et les pièges du sanctuaire sans risque",
          hi: "बिना किसी जोखिम के शुरुआती स्थिति और केंद्रीय जाल का अभ्यास करें",
          zh: "零风险揣摩前置布子阵型与中央避难格包抄战术",
        },
        tag: {
          ar: "تكتيك فرعوني",
          en: "Ancient Tactics",
          es: "Táctica Antigua",
          fr: "Tactique Antique",
          hi: "प्राचीन रणनीति",
          zh: "古法棋策",
        },
        badge: {
          ar: "مجاني",
          en: "Free",
          es: "Gratis",
          fr: "Gratuit",
          hi: "मुफ़्त",
          zh: "免费特训",
        },
      },
      friend: {
        title: {
          ar: "نزال سيجة مع صديق",
          en: "Private Seega Sanctuary",
          es: "Santuario Privado de Seega",
          fr: "Sanctuaire Privé de Seega",
          hi: "दोस्त के साथ निजी सीगा",
          zh: "好友私密玄石古棋对决",
        },
        desc: {
          ar: "تحدَّ صديقك في مبارزة تراثية أصيلة بقواعد السيجة المعمول بها",
          en: "Direct invite to experience ancient Egyptian strategy with a friend",
          es: "Invita a un amigo a un duelo de estrategia del antiguo Egipto",
          fr: "Invitez un ami pour un duel de stratégie d'Égypte antique",
          hi: "दोस्त के साथ प्राचीन मिस्र की रणनीति का अनुभव करने के लिए सीधा आमंत्रण",
          zh: "专属链接直邀好友，方寸砂石格间共研古埃及战神之道",
        },
        tag: {
          ar: "تراث واستراتيجية",
          en: "Heritage Match",
          es: "Partida Clásica",
          fr: "Partie Classique",
          hi: "विरासत मैच",
          zh: "古风弈战",
        },
        badge: {
          ar: "رابط خاص",
          en: "Direct Link",
          es: "Enlace Directo",
          fr: "Lien Direct",
          hi: "सीधा लिंक",
          zh: "直约私房",
        },
      },
      match: {
        title: {
          ar: "نزال رمال النيل التنافسي (1 ضد 1)",
          en: "Ranked Seega Arena (1v1)",
          es: "Arena Clasificatoria de Seega",
          fr: "Arène Classée de Seega (1v1)",
          hi: "रैंक्ड सीगा अखाड़ा (1v1)",
          zh: "天梯排位玄石截杀现金战 (1对1)",
        },
        desc: {
          ar: "توفيق فوري والجوائز النقدية لمن يستنزف أو يحصر كافة أحجار الخصم",
          en: "Real-money duel where capturing or trapping all opponent stones wins",
          es: "Duelo por dinero donde capturar o bloquear las piedras rivales gana",
          fr: "Duel avec enjeu où capturer ou piéger toutes les pierres gagne",
          hi: "वास्तविक नकद मुकाबला जहाँ विरोधी के सभी पत्थरों को फंसाने वाला जीतता है",
          zh: "排位秒级匹配，以截杀锁死对手全盘玄石者问鼎全额奖金",
        },
        tag: {
          ar: "جوائز نقدية",
          en: "Cash Pot",
          es: "Bote en Efectivo",
          fr: "Cagnotte en Cash",
          hi: "नकद पॉट",
          zh: "现金结算",
        },
        badge: {
          ar: "تنافسي",
          en: "Ranked",
          es: "Clasificatorio",
          fr: "Classé",
          hi: "रैंक्ड",
          zh: "排位决胜",
        },
      },
      tournament: {
        title: {
          ar: "كأس فراعنة السيجة الكبرى",
          en: "Pharaohs of Seega Cup",
          es: "Copa Faraones de Seega",
          fr: "Coupe des Pharaons de Seega",
          hi: "फैरो सीगा कप",
          zh: "法老玄石争霸大师赛",
        },
        desc: {
          ar: "تصفيات إقصائية يتنافس فيها أمهر دهاة التكتيك الصحراوي",
          en: "Single-elimination championship for masters of ancient Nile encirclement",
          es: "Campeonato eliminatorio para maestros del asedio del Nilo",
          fr: "Championnat éliminatoire pour les maîtres de l'encerclement antique",
          hi: "प्राचीन रणनीति के उस्तादों के लिए सिंगल-एलिमिनेशन चैम्पियनशिप",
          zh: "尼罗围杀高手齐聚单败决战，赢取法老金杯与巨额大奖",
        },
        tag: {
          ar: "كأس الفراعنة",
          en: "Pharaohs Cup",
          es: "Copa Faraón",
          fr: "Coupe Pharaon",
          hi: "फैरो कप",
          zh: "法老金杯",
        },
        badge: {
          ar: "جوائز كبرى",
          en: "Big Pool",
          es: "Gran Bote",
          fr: "Grande Cagnotte",
          hi: "बड़ा पूल",
          zh: "丰厚奖赏",
        },
      },
    },
  },
};

/**
 * Safe accessor for any game's theme tokens with guaranteed fallback.
 */
export function getGameThemeTokens(gameId: string): GameThemeTokens {
  const normalized = gameId.toLowerCase();
  const existing = GAME_THEME_TOKENS[normalized];
  if (existing) {
    return existing;
  }
  // Fallback to chess theme token defaults
  const fallback = GAME_THEME_TOKENS.chess as GameThemeTokens;
  return {
    ...fallback,
    gameId,
  };
}

