/**
 * Server-authoritative Backgammon rules.
 *
 * ============================================================================
 * RULESET: Nizalo Backgammon Ruleset v1 -- Standard Backgammon, single game,
 * no doubling cube
 * ============================================================================
 * This is the ONE launch ruleset. It does not mix in Nackgammon, Hypergammon,
 * Acey-Deucey, or any variant starting position or entry rule. Every rule
 * below is drawn from a single, internally consistent base: standard
 * Western backgammon movement, hitting, the bar, entering, and bearing off.
 *
 *   - Board: 24 points. Seat 0 moves from point 24 toward point 1 (absolute
 *     index 23 down to 0); seat 1 moves the mirror direction, point 1
 *     toward point 24 (absolute index 0 up to 23). Seat 0's home board is
 *     indices 0-5 (their own points 6-1); seat 1's home board is indices
 *     18-23 (their own points 6-1, mirrored). This file works entirely in
 *     the shared absolute index space, never in either player's own
 *     point-numbering -- that numbering is a presentation convention this
 *     engine has no need for.
 *   - Standard starting position, 15 checkers per side: seat 0 has 2 on
 *     idx23, 5 on idx12, 3 on idx7, 5 on idx5; seat 1 mirrors it exactly
 *     (2 on idx0, 5 on idx11, 3 on idx16, 5 on idx18).
 *   - Opening roll: each player rolls one die; the higher roller leads and
 *     that first turn is played using the two (necessarily different)
 *     values just rolled, exactly as if they had been rolled together. A
 *     tie is rerolled. Both this contest and every dice roll thereafter
 *     are generated by the SERVER from this duel's own private seed --
 *     never a value a client supplies or can predict (see this file's
 *     own rngFrom()/rollDiceFor(), the same construction Speed Math and
 *     Dominoes use for their own server-side randomness).
 *   - Turn sequence: on your turn you have 2 dice values to use (4, all
 *     equal, on a double). If you have a checker on the bar, it MUST be
 *     entered (into the opponent's home board, at the point the die
 *     value indicates) before any other checker may move. A checker may
 *     land on an empty point, a point already held by your own checkers,
 *     or a point held by exactly ONE opposing checker (a "blot") -- which
 *     HITS it, sending it to the bar. A point held by two or more
 *     opposing checkers is blocked. You must play a die if the position
 *     allows any legal action for it; you may only pass on a die that
 *     has genuinely no legal action available for it, and passing is
 *     always re-verified against the real position, never trusted from
 *     the client.
 *   - Bearing off is legal only once ALL of a player's own checkers
 *     (nothing on the bar, nothing outside their home board) are inside
 *     their own home board. A die that exactly matches a checker's
 *     distance from bearing off may bear it off; a die LARGER than any
 *     occupied point's distance may bear off the checker on the
 *     farthest-out occupied point instead (the standard "overage" rule).
 *   - Win: the first player to bear off all 15 checkers wins immediately.
 *   - Scoring: if the loser has borne off ZERO checkers, the win is a
 *     GAMMON (worth double); if the loser additionally still has a
 *     checker on the bar or anywhere in the WINNER's home board, it is a
 *     BACKGAMMON (worth triple). Otherwise it is a single game. This
 *     multiplier is carried on the outcome for display and any stakes
 *     payout; the abstract rating score (see plugin.mjs's own score())
 *     stays on the same win/loss/draw scale every launch game uses.
 *   - Draw: backgammon has no draw condition under these rules. Every
 *     game resolves to a winner -- "draw" is simply not applicable here.
 *   - Special cases, explicitly scoped for v1:
 *       1. NO DOUBLING CUBE. Every duel is played as a flat single game
 *          for its own stake; the cube (offering/accepting/declining a
 *          double mid-game) is a deliberately deferred feature, not an
 *          oversight.
 *       2. Mandatory dice usage is enforced per remaining die, checked
 *          against the CURRENT position each time: a die may be played
 *          if it has a legal action available right now. This engine
 *          does NOT run the full two-ply lookahead some implementations
 *          use to force the specific dice ORDER that maximises how many
 *          of the two (or four) dice end up playable in the rare
 *          position where one order permits both dice and the other
 *          permits only one -- a genuinely known, bounded simplification
 *          for this launch version, not a silent gap.
 *       3. Resignation and timeout are handled entirely by the generic
 *          duel engine (packages/duel-engine/src/duel.mjs's own resign()
 *          and per-seat clock) -- this plugin adds no special-case code
 *          for either, exactly like every other ALTERNATING launch game.
 *
 * Pure functions over an explicit state object -- no module-level mutable
 * state, no clock, no I/O, the same discipline as every other ruleset
 * module in this codebase.
 */

export const SEAT_0 = 0, SEAT_1 = 1;
export const POINTS = 24;
export const CHECKERS_PER_SIDE = 15;

export function other(seat) {
  return seat === SEAT_0 ? SEAT_1 : SEAT_0;
}

/** Standard starting position -- see this file's own header. Positive
 * values are seat 0 checkers, negative are seat 1, magnitude is count. */
export function initialBoard() {
  const board = new Array(POINTS).fill(0);
  board[23] = 2; board[12] = 5; board[7] = 3; board[5] = 5;
  board[0] = -2; board[11] = -5; board[16] = -3; board[18] = -5;
  return board;
}

export function pointSeat(value) {
  if (value > 0) return SEAT_0;
  if (value < 0) return SEAT_1;
  return null;
}

export function isHomeIndex(seat, idx) {
  return seat === SEAT_0 ? idx <= 5 : idx >= 18;
}

/** How many pips a checker at `idx` still needs to bear off entirely. */
export function distanceToOff(seat, idx) {
  return seat === SEAT_0 ? idx + 1 : POINTS - idx;
}

export function destinationFor(seat, from, die) {
  return seat === SEAT_0 ? from - die : from + die;
}

export function isBearOffDestination(seat, dest) {
  return seat === SEAT_0 ? dest < 0 : dest >= POINTS;
}

/** Where a checker re-entering from the bar lands for a given die --
 * always somewhere in the OPPONENT's home board (see this file's own
 * header on why that is the correct, standard rule, not a mirror bug). */
export function entryDestination(seat, die) {
  return seat === SEAT_0 ? POINTS - die : die - 1;
}

export function isOpenFor(seat, idx, board) {
  const v = board[idx];
  if (v === 0) return true;
  if (pointSeat(v) === seat) return true;
  return Math.abs(v) === 1; // a lone blot may be landed on (and hit)
}

export function allCheckersHome(seat, board, bar) {
  if (bar[seat] > 0) return false;
  for (let idx = 0; idx < POINTS; idx++) {
    if (pointSeat(board[idx]) === seat && !isHomeIndex(seat, idx)) return false;
  }
  return true;
}

export function isLegalBearOff(seat, from, die, board, bar) {
  if (!allCheckersHome(seat, board, bar)) return false;
  if (pointSeat(board[from]) !== seat || !isHomeIndex(seat, from)) return false;
  const dist = distanceToOff(seat, from);
  if (die === dist) return true;
  if (die < dist) return false;
  // Overage rule: legal only if `from` is the farthest-out occupied point
  // in the home board -- no seat checker sits at a point still farther
  // from bearing off than this one.
  for (let idx = 0; idx < POINTS; idx++) {
    if (pointSeat(board[idx]) === seat && isHomeIndex(seat, idx) && distanceToOff(seat, idx) > dist) return false;
  }
  return true;
}

/** Every legal `{ from, die, to }` for `seat` using exactly this one die
 * value against the CURRENT position. `to` is `"OFF"` for a bear-off, an
 * absolute index otherwise. `from` is `"BAR"` when entering. */
export function legalActionsForDie(state, seat, die) {
  const { board, bar } = state;
  if (bar[seat] > 0) {
    const dest = entryDestination(seat, die);
    return isOpenFor(seat, dest, board) ? [{ from: "BAR", die, to: dest }] : [];
  }
  const actions = [];
  for (let idx = 0; idx < POINTS; idx++) {
    if (pointSeat(board[idx]) !== seat) continue;
    const dest = destinationFor(seat, idx, die);
    if (isBearOffDestination(seat, dest)) {
      if (isLegalBearOff(seat, idx, die, board, bar)) actions.push({ from: idx, die, to: "OFF" });
    } else if (isOpenFor(seat, dest, board)) {
      actions.push({ from: idx, die, to: dest });
    }
  }
  return actions;
}

/** Every legal action for `seat` across all currently DISTINCT remaining
 * dice values (a double's repeats all behave identically at one instant,
 * so checking each distinct value once is exact, not an approximation). */
export function legalActions(state, seat) {
  const distinct = [...new Set(state.dice)];
  const all = [];
  for (const die of distinct) all.push(...legalActionsForDie(state, seat, die));
  return all;
}

export function hasAnyLegalAction(state, seat) {
  return legalActions(state, seat).length > 0;
}

/**
 * Deterministic PRNG (mulberry32 over an FNV-1a hashed seed) -- the same
 * construction every other plugin in this codebase uses for its own
 * seeded randomness. This is what makes a dice roll reproducible in a
 * replay/audit while remaining something no client can predict or
 * supply -- see game-speed-math/src/plugin.mjs's own header.
 */
export function rngFrom(seed) {
  let h = 2166136261 >>> 0;
  for (const ch of String(seed)) {
    h ^= ch.charCodeAt(0);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return function next() {
    h |= 0; h = (h + 0x6d2b79f5) | 0;
    let t = Math.imul(h ^ (h >>> 15), 1 | h);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function d6(rnd) {
  return 1 + Math.floor(rnd() * 6);
}

/** One ordinary in-game roll: two dice, or four copies on a double. Keyed
 * by `${seed}:roll:${rollIndex}` -- a distinct, never-reused namespace
 * from the opening contest below, so the two can never collide. */
export function rollDiceFor(seed, rollIndex) {
  const rnd = rngFrom(`${seed}:roll:${rollIndex}`);
  const a = d6(rnd), b = d6(rnd);
  return a === b ? [a, a, a, a] : [a, b];
}

/** The opening contest: each side rolls one die, rerolling on a tie, and
 * the higher roller leads with those two (distinct) values as their
 * first turn's dice -- the standard convention. Bounded reroll loop
 * purely as defensive coding; a real tie streak this long is not
 * statistically reachable. */
export function openingRoll(seed) {
  for (let attempt = 0; attempt < 1000; attempt++) {
    const rnd = rngFrom(`${seed}:open:${attempt}`);
    const a = d6(rnd), b = d6(rnd);
    if (a !== b) return { leader: a > b ? SEAT_0 : SEAT_1, dice: [a, b], attempts: attempt + 1 };
  }
  // Unreachable in practice; keeps the function total.
  return { leader: SEAT_0, dice: [1, 2], attempts: 1000 };
}
